### ISSUE TITLE
assign data array not work

### ISSUE THREAD

**Issue by freshgoldprice** [sergiodlopes/jquery-flexdatalist#1]
var data = [];
$('.larg-list a,.small-list a').each(
	function(){
		var text = $(this).text();
		var url = $(this).attr("href");
		var cat = $(this).closest('Section').attr('id');
		var id = $(this).data("id");
		
		var myitem = new item(text, url, cat, id);
		
		data[data.length] = myitem;
});

function item(text, url, cat, id) {
    this.text = text;
    this.url = url;
    this.cat = cat;
    this.id = id;
}

//assign array of object data not word
$('#srch-term').flexdatalist({
	minLength: 1,
	searchIn: 'text',
	data: data
	});

**Comment by sergiodlopes** [comment]
Hi,

In order to better understand the problem, please explain what you're trying to achieve/do.

Thanks!

**Comment by freshgoldprice** [comment]
i create array of object and assign it in option parm data, when i search get data array null

it work fine with detalis list or file url

**Comment by sergiodlopes** [comment]
I'm checking the problem.

Thanks!

**Comment by freshgoldprice** [comment]
i will add demo for this probleam

**Comment by sergiodlopes** [comment]
no need!

Pushing fix.

**Comment by sergiodlopes** [comment]
Download the latest version and check if it works as expected now.

Thanks!

**Comment by freshgoldprice** [comment]
thank you for your support

**Comment by sergiodlopes** [comment]
Have you tested it?

**Comment by freshgoldprice** [comment]
ya is very good thank you

**Comment by sergiodlopes** [comment]
You're welcome!
