### ISSUE TITLE
Support dropdown with no input

### ISSUE THREAD

**Issue by schang933** [sergiodlopes/jquery-flexdatalist#10]
Preferably have an option to dropdown without any user input, like the native datalist implementation.

![datalist image](http://www.binaryintellect.net/articles/content/Images/T_AutocompleteDataListMVC_01.png)

I'm really interested in using this as cross-browser support is finicky and it seems to be one of the few plugins with recent activity.

**Comment by sergiodlopes** [comment]
Hi,

At the moment you can show all the results on input focus. Just set option 'minLenght' to 0. It doesn't have the down arrow (at the moment), thought.

Hope this helps.

Sérgio

**Comment by schang933** [comment]
Thanks @sergiodlopes! I saw your message in #2 as well and the minLength method is a better solution I think. If you would like feel free to close this issue.

**Comment by sergiodlopes** [comment]
Great! Glad that it's enough.

Sérgio
