### ISSUE TITLE
JSON array inside object

### ISSUE THREAD

**Issue by ezdavis** [sergiodlopes/jquery-flexdatalist#101]
I've tried using dot notation and bracket notation but can't get either to work. Lets say for example my JSON looks like this 
`[
  {
   "name": "Jane Doe",
   "address": "1 main street"
  },
  {
   "name": "John Doe",
   "addresss": "2 main street"
  }
]`
which is similar to your examples and it works fine. However my JSON looks likes this instead 
`{
"Selection1":[
  {
   "name": "Jane Doe",
   "address": "1 main street"
  },
  {
   "name": "John Doe",
   "addresss": "2 main street"
  }
]}` 
which makes it not work. I need to have it work with the second way the JSON is formatted. Any ideas?

**Comment by sergiodlopes** [comment]
Hi,

Yeah, it's not possible at the moment. Not sure if it would make sense that level of customization  You would need to reformat the JSON structure before passing data on to flexdatalist.

`[ { "type":"Selection1","name": "Jane Doe", "address": "1 main street" }, { "type":"Selection1","name": "John Doe", "addresss": "2 main street" } ]`
