### ISSUE TITLE
Selection Required on Multiple

### ISSUE THREAD

**Issue by rmaspero** [sergiodlopes/jquery-flexdatalist#105]
So I have a simple multiple field option with selection required.This appears to be working fine and acts the same as the demo on the site. 
However I noticed that whilst for other inputs selection required clears the input field if the selection isn't valid for some reason here it does not. The value returned is empty but the text in the input is not cleared?

**Comment by sergiodlopes** [comment]
Hi,

Please check latest release if the problem persists.

Thank you!
Sérgio
