### ISSUE TITLE
Values not being updated when removing items.

### ISSUE THREAD

**Issue by shornuk** [sergiodlopes/jquery-flexdatalist#109]
On latest version, using `limitOfValues`. When I delete an item, it removes visually, however the value is not being updated so no values are ever removed and any new ones are just being added.

Any ideas?

**Comment by sergiodlopes** [comment]
Hi,

Check out latest release pls.

Thanks!
Sérgio

**Comment by shornuk** [comment]
I have the latest releases. 2.2.0.

**Comment by sergiodlopes** [comment]
Hi,

@shornuk Sorry, I released 2.2.1 with the fix. I was refering to that release. :)

Sérgio

**Comment by samhibberd** [comment]
Hi @sergiodlopes, we are still running into this issue with 2.2.2?

Thanks,

Sam
