### ISSUE TITLE
Order of elements seems to affect usability

### ISSUE THREAD

**Issue by schang933** [sergiodlopes/jquery-flexdatalist#11]
Hey, back again. Sorry I was stuck on this for a few hours, and seem to have just diagnosed it.

This works great:
```html
<link rel="stylesheet" href="public/css/jquery.flexdatalist.min.css">
<script src="https://code.jquery.com/jquery-3.1.0.min.js" integrity="sha256-cCueBR6CsyA4/9szpPfrX3s49M9vUU5BgtiJj06wt/s=" crossorigin="anonymous"></script>
<script src="public/js/jquery.flexdatalist.min.js"></script>

<input class="flexdatalist yesNoData" type="text" name="dataField">

<script type="text/javascript">
$(document).ready(function() {
  $('.flexdatalist.yesNoData').flexdatalist({
    minLength: 0,
    valueProperty: 'value',
    visibleProperties: ['name'],
    searchIn: 'name',
    data: [
      {
        name: 'Yes',
        value: 'YES'
      },
      {
        name: 'No',
        value: 'NO'
      }
    ]
  });
});
</script>
```

This does not:
```html
<link rel="stylesheet" href="public/css/jquery.flexdatalist.min.css">
<script src="https://code.jquery.com/jquery-3.1.0.min.js" integrity="sha256-cCueBR6CsyA4/9szpPfrX3s49M9vUU5BgtiJj06wt/s=" crossorigin="anonymous"></script>

<input class="flexdatalist yesNoData" type="text" name="dataField">

<script src="public/js/jquery.flexdatalist.min.js"></script>

<script type="text/javascript">
$(document).ready(function() {
  $('.flexdatalist.yesNoData').flexdatalist({
    minLength: 0,
    valueProperty: 'value',
    visibleProperties: ['name'],
    searchIn: 'name',
    data: [
      {
        name: 'Yes',
        value: 'YES'
      },
      {
        name: 'No',
        value: 'NO'
      }
    ]
  });
});
</script>
```

Note the only change is moving where the library is being imported. Are you waiting for the document to finish loading before starting any business logic?

**Comment by sergiodlopes** [comment]
Hey,

The plugin autodiscovers all '.flexdatalist' input's on initialization.

I would recommend placing the configuration in the input's data attributes:

`<input class="flexdatalist yesNoData" data-min-length="0" data-value-property="value" data-visible-properties='["name"]' data-search-in="name" type="text" data-data='[{name:"Yes" ...}]' name="dataField">`

**Comment by schang933** [comment]
Hm, interesting. So if I just remove the "flexdatalist" class, it works fine.

While your suggestion works for me now, I think more people in the future will get confused with your library. I might consider resetting inputs if the user manually initializes a flexdatalist on the element again to avoid this confusion, or having warning messages that flexdatalists already exist on some classes. Currently it "fails" silently.

**Comment by sergiodlopes** [comment]
Yeah, I agree. Good suggestion. I'll implement that in the next version. Thanks! :)

Sérgio

**Comment by sergiodlopes** [comment]
Hey,
On 1.7.0 you should be able to reset plugin just by re-initializing it. :)

Thanks.
Sérgio
