### ISSUE TITLE
change:flexdatalist event not firing

### ISSUE THREAD

**Issue by jonhue** [sergiodlopes/jquery-flexdatalist#110]
```js
$('input.flexdatalist').flexdatalist();

$('input.flexdatalist.fetchUnits').on( 'change:flexdatalist', function(event, set, options) {
    alert(set.value);
});
```

Neither does the alert show up, nor does the console mention any errors.
Everything else works fine.

**Comment by sergiodlopes** [comment]
Hi,

What kind of change is supposedly happening?

Thanks!
Sérgio

**Comment by jonhue** [comment]
@sergiodlopes I am using a default input (no multiselect). It should fire whenever an option got selected and the change has been reflected in the value of the input.

**Comment by sergiodlopes** [comment]
@jonhue I tested on documentation page (v2.2.1, check browser console for trigger logs) and it seems to be working fine.
Are you using the latest version? If so, I must be missing something...

**Comment by jonhue** [comment]
@sergiodlopes Oh, I found my mistake. Thanks for your help!

**Comment by jonhue** [comment]
@sergiodlopes  One more question: I have updated to the master version, and flexdatalist is now removing the placeholder when initialized on an input (it did not previously). Is that intended?

**Comment by sergiodlopes** [comment]
@jonhue Not intended. It was missing from input's alias. v2.2.2 has a fix.

Sérgio
