### ISSUE TITLE
Enter not working triggering when the string is found.

### ISSUE THREAD

**Issue by Reginwaldt** [sergiodlopes/jquery-flexdatalist#112]
Hi ,
I am new to flexdatalist plugin and I can't get the' Enter' button to work when the full string on the input is available within my search list.At the moment this is my code

    `var inputCustAccount = $('#inputCustAcc').flexdatalist({
                    minLength: 1,
                    valueProperty: '*',
                    selectionRequired: false,
                    visibleProperties: ["StoreName","CustomerPastelCode"],
                    searchIn: 'CustomerPastelCode',
                    data: finalData
                });
                inputCustAccount.on('select:flexdatalist', function (event, data) {

                    $('#inputCustAcc').val(data.CustomerPastelCode);
                    $('#inputCustName').val(data.StoreName);
                    $('#inputDeliveryDate').focus();
                    $('#creditLimit').val(data.CreditLimit);
                    $('#balDue').val(parseFloat(data.BalanceDue).toFixed(2));
                    $('#boozeLisence').val(data.UserField5);
                    $("#submitFilters").prop("disabled", false);
                    $('#customerEmail').val(data.Email);
                    GlobalcustomerId = data.CustomerId;
                });` 
When I hit enter nothing happens unless I click on the item and hit enter

Thanks in advance

**Comment by sergiodlopes** [comment]
Hi @Reginwaldt,

Flexdatalist expects something to be selected when pressing enter. You can add `focusFirstResult: true` to your flexdatalist options. It will auto focus/select the first result.

Hope it helps.
Thanks!
Sérgio

**Comment by Reginwaldt** [comment]
Wow ,thank you very much i thought it  needed lots of JS code but one line works perfect .Thanks again, I am changing all my autocomplete to Flexdatalist.

**Comment by sergiodlopes** [comment]
@Reginwaldt Glad it worked :)

Closing issue.

Sérgio
