### ISSUE TITLE
List does not disappear on tab away

### ISSUE THREAD

**Issue by schang933** [sergiodlopes/jquery-flexdatalist#12]
If a user is tabbing through form inputs, the datalist stays visible until the user tabs into the next flexdatalist input.

The datalist should preferably disappear as soon as the user tabs away.

If you point me to the place in code where this is happening, I may be able to do a PR for you. Though word of caution I'm not a frontender.

**Comment by sergiodlopes** [comment]
Hey,

Nice catch :) Thanks!

Sérgio

**Comment by sergiodlopes** [comment]
Hey,
Fixed on 1.7.0! Thanks.

Sérgio
