### ISSUE TITLE
Feature request: option to disable search

### ISSUE THREAD

**Issue by schang933** [sergiodlopes/jquery-flexdatalist#13]
If selectionRequired is false, a input's value can be different if a user only types it vs selects it.

But for our use case the user needs to be able to type any custom string. Disabling the search feature will help prevent users from accidentally typing their selection instead of selecting it.

Edit: I (or someone else who stumbles on this issue) may also be able to help with this if you can point me to the right places in the code.

**Comment by sergiodlopes** [comment]
If I understood correctly, If I added a `searchEnabled` option, allowing to disable search, would solve that?

**Comment by schang933** [comment]
Not solve the issue, but help it. E.g. suppose an option's name is "Yes" with value "YES". If the user types "Yes", the value will be "Yes" instead of "YES". This is a trivial example, but may screw up backend parsing.

A malicious user will always be able to get around this design, but the goal is to prevent a normal user from accidentally searching and finish typing a value that should have been selected.

Thanks for your quick responses by the way!

**Comment by sergiodlopes** [comment]
Like you refered to in your first comment, if `selectionRequired ` is set to `false`, whatever the user writes in the field, will send it. That's the desired behavior. Maybe it's a bug. :)
Having said that, yeah, having the option to disable search, it's not a bad idea.

No problem, thanks for helping improve the plugin. :)

**Comment by sergiodlopes** [comment]
Hey,
`searchDisabled `option added on 1.7.0! Thanks.

Sérgio
