### ISSUE TITLE
Need to display id and value

### ISSUE THREAD

**Issue by SureshHV** [sergiodlopes/jquery-flexdatalist#138]
Hi,

I am using flexdatalist with json and I need to display both id and value.  I am using 2.2 version and I am able to get either id or value but I need to get id and value. Could you please help me on this?

**Comment by jotahws** [comment]
You need to place your attibutes in an array using the option `visibleProperties`: 

```
$('#concursoInput').flexdatalist({
        `visibleProperties: ['value', 'id'],`
        data: yourJSON,
});
```

If you want to style one of your properties a little by adding a parenthesis for example, all you have to do is:
`visibleProperties: ['value', '({id})']`

**Comment by SureshHV** [comment]
Thanks dude, I tried your way and its working like a charm 👍
