### ISSUE TITLE
Show no results text when no matching elements

### ISSUE THREAD

**Issue by JohnnyEnc** [sergiodlopes/jquery-flexdatalist#16]
How do i add a record that says *No records found* when no elements are matched?

**Comment by sergiodlopes** [comment]
Hi,

At the moment that's not supported natively. I'll implement that in a future release.
It's possible to implement it, though, using the event `after:flexdatalist.search ` and onblur (to remove the "no records found").

**Comment by sergiodlopes** [comment]
Hi,

On release 1.8.0 it shows "No results found". You're able to customize the text with the option `noResultsText`.

**Comment by JohnnyEnc** [comment]
Works great, thanks!
