### ISSUE TITLE
Delete a 'multiple' tag

### ISSUE THREAD

**Issue by NeilJS** [sergiodlopes/jquery-flexdatalist#17]
This is very comprehensive. Just one thing that jumps out at me - it would be good to have the ability to remove 'multiple' tags by using the backspace key, not just the 'x' button on the tag.
Great work!

**Comment by sergiodlopes** [comment]
Hi,

Yeah, it's a great suggestion, from the usability Pointer of view. I'll implement it.

Thanks!

**Comment by sergiodlopes** [comment]
Hi,

Pressing backspace key on input multiple, will remove values on release 1.8.0.
