### ISSUE TITLE
reset (empty) values for multiple autocomplete

### ISSUE THREAD

**Issue by sconstro** [sergiodlopes/jquery-flexdatalist#18]
I am using version 1.8.1 and I have a multiple autocomplete and I cannot reset values (clear selections)
Example:
I selected Value 1 and Value 2. I did  $('#salesChannel').val('') but the values still appear on the screen.
I also added $('#salesChannel').parent().find("ul.flexdatalist-multiple li.value").remove().
Now the screen is empty as expected. When I try again the autocompletion I can see Value 3, Value 4 but not anymore Value 1 and Value 2
I suppose there is a list of previously selected values which I don't know how to clear.

**Comment by sergiodlopes** [comment]
Hi,

I'll fix that later today.
You're on the right track, try this for now:
`$('#salesChannel').val('').parent().find("ul.flexdatalist-multiple li.value").remove();`

**Comment by sergiodlopes** [comment]
Hi,

It should work now (1.8.2).

Cheers,
Sérgio
