### ISSUE TITLE
datalist - label vs value

### ISSUE THREAD

**Issue by sconstro** [sergiodlopes/jquery-flexdatalist#19]
Thank you for your previous quick fix. By the way, it's a great plugin.
Another small bug:
$('#' + list).find('option').each(function () {
                    var val = $(this).val();
                    _options.data.push({
                        **label: val,**
                        value: val
                    });
Instead of label: val  I think it should be label: $(this).text() because in datalist option you have pairs of value-text.

**Comment by sergiodlopes** [comment]
Hi,

No problem. Hope it's useful to you. ☺

Yeah, it's a good point. In this case I followed what appears to be the HTML5 standard (please see the example with (weirdly) unclosed option tag):
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist

Having said that, I'll add support for option's text as label.

Cheers,
Sérgio

**Comment by sergiodlopes** [comment]
Added support for datalist's text as label on 1.8.3

Thanks!
