### ISSUE TITLE
Auto select record.

### ISSUE THREAD

**Issue by carlosbrunoro** [sergiodlopes/jquery-flexdatalist#197]
how can I select a single record automatically?
Como eu posso selecionar um único registro automaticamente?

**Comment by marcipriano** [comment]
Could you resolve the issue?

**Comment by carlosbrunoro** [comment]
I solved, thank you

**Comment by marcipriano** [comment]
I have the same problem. Can you share the solution?

**Comment by carlosbrunoro** [comment]
`function obtem_destino(p_id_motivo) {
	$('input.flexdatalist').flexdatalist();
	$('input.flexdatalist').flexdatalist('url', '/Ocorrencia/obtem_destino/' + p_id_motivo);

	// get json da URL.
	$.getJSON('/Ocorrencia/obtem_destino/' + p_id_motivo, function(data) {
		// Check json size.
		var count = Object.keys(data).length;

		// Check json size and select record for user.
		if (count == 1) {
			$('input.flexdatalist').flexdatalist('value', data[0].id_destino);
		}
	});
}`

**Comment by carlosbrunoro** [comment]
function obtem_destino(p_id_motivo) {
	$('input.flexdatalist').flexdatalist();
	$('input.flexdatalist').flexdatalist('url', '/Ocorrencia/obtem_destino/' + p_id_motivo);

	// get json da URL.
	$.getJSON('/Ocorrencia/obtem_destino/' + p_id_motivo, function(data) {
		// Check json size.
		var count = Object.keys(data).length;

		// Check json size and select record for user.
		if (count == 1) {
			$('input.flexdatalist').flexdatalist('value', data[0].id_destino);
		}
	});
}
