### ISSUE TITLE
How to display list ? 

### ISSUE THREAD

**Issue by byinff** [sergiodlopes/jquery-flexdatalist#2]
Hi Sir,

How can i do to display the list and select an option?

Very thanks for this amazing plugins.

Congratulations.

**Comment by sergiodlopes** [comment]
Hi,

What do you mean by that?

**Comment by byinff** [comment]
Hi,

when i write, this plugin shows me coincidens but i can't display the total options from autocomplete when i click the dropdown.

**Comment by sergiodlopes** [comment]
Like a `<select>`?

**Comment by byinff** [comment]
Yes, when i click a combo to write, display the options available

**Comment by sergiodlopes** [comment]
I see. This plugin by design, is not supposed to work as a select (for that you have the excellent [chosen](https://harvesthq.github.io/chosen/) jQuery plugin). Its goal is to allow more flexibility to datalist/inputs autocomplete functionality.
