### ISSUE TITLE
clear value on multiple values input

### ISSUE THREAD

**Issue by sconstro** [sergiodlopes/jquery-flexdatalist#20]
Hi,
After you commited and fixed the "clear value on multiple values input", it is not working anymore to clear the single input:
Before this code used to work:
$('#customerId-flexdatalist').val('');
    $('#customerId').val('');

Now, it brings back after 2-3 seconds (window.timeout!?) the previous value.

**Comment by sergiodlopes** [comment]
hi,

It should be fixed on 1.8.4

Thanks!
Sérgio
