### ISSUE TITLE
Question : how to allow values not in the list ? 

### ISSUE THREAD

**Issue by cavo789** [sergiodlopes/jquery-flexdatalist#21]
Hi Sergio.

First of all, thank you for your great and amazing plugin.  Really nice.  Congrats !

Small question : how to allow the user to type a value that is not in the datalist ?  

My wish : I've filled in the datalist with tags.  By selecting a value, I've on "onExit" trigger and make an ajax request against my server who respond with a json answer.  Just like a search engine.  That works great (like your "countries multiple select" examples)

Now I would like to allow the user to type a new value, not in the data-list, and then search for that value.

Can you guide me please ?

Thanks a lot.

**Comment by sergiodlopes** [comment]
Hi,

Thanks!

Like a normal input, but for multiple values?

**Comment by cavo789** [comment]
So quick, thanks !

I'm writing a php application, open source (available on github/cavo789/markdown), demo here : http://markdown.cavo789.com/ 

See at the top left : I'm currently using the Selectize.js plugin.   Yours is better.  But my need is to allow to choice or to type, just like you'll see...   I wish to make easier the entry of a search term (existing tags) or to allow new ones.

Is it clear enough ? 

Thank you Sergio !

**Comment by sergiodlopes** [comment]
No problem.

If I understood correctly, with flexdatalist, everything you write in the field (unless `multiple: true` and `selectionRequired: true`) is the value. You'll just need to be "listening" to the change event.

Does this help?

**Comment by cavo789** [comment]
I'm not sure to correctly understand...

On your demo site (http://projects.sergiodinislopes.pt/flexdatalist/), you've the first demo in chapter "DATALIST" where we can select one or more languages (the example starting with `Multiple options from <datalist> (selection required)`).

I can then type `PHP` and `Pascal` f.i.   Is it possible to allow the value `HTML` (not in your list) : I'll type `HTML` and press enter so I'll confirm that word.  So, ideally, it would be cool to allow existing values (PHP & Pascal) and new ones (HTML).

In my real-life need : allow to select `Projects`, `Work`, `2016` f.i. to allow me to search files with these three words.   `Projects` and `Work` will be in the datalist and `2016` not, manually filled in.

**Comment by sergiodlopes** [comment]
Got it.

Yeah, you can use the example "Multiple options from <datalist> (Use comma to set and separate values)", the difference is that to set the value, you'll need to press "comma".

Having said that, your "enter" suggestion to set the value, is a good one.

**Comment by cavo789** [comment]
Damned !  Need to press `comma` and not `Enter`.
You made my day :+1:  so it's possible and native.  Great.  Perhaps, yes, Enter would be great, more intuitive.

Thanks a log Sergio !

**Comment by sergiodlopes** [comment]
No problem!

Check out release 1.8.5. Should work with "enter" key press now.

Cheers!

**Comment by Krumator** [comment]
Hi,
I tried this plugin just new today. Works Great fro me. I'M sorry I cannot share my files where I use it because it is like Company data I am using for my project (inhouse). 
But What I need :
1- I use your script to put multiple data by easily clicking on the suggestions. 
2 - The records are fine. But When I need to Updat the company record, the written data is there, When I want to Add or change something : How can I reactivate the script "Whitout REsetting the Placeholder for the Pre-entered values in the INPUT?
