### ISSUE TITLE
.flexdatalist is not a function

### ISSUE THREAD

**Issue by Aibat1997** [sergiodlopes/jquery-flexdatalist#215]
I install it and make all steps from your website but I get this error:  jQuery(...).flexdatalist is not a function

**Comment by vincenthawke** [comment]
> I install it and make all steps from your website but I get this error: jQuery(...).flexdatalist is not a function

How did you solve this issue? Is it something with load order?

**Comment by Aibat1997** [comment]
Hi, the error was when I declare option I only write value like this
<option value="something">, you must change it to this <option
value="something">something</option>.
I hope that it will help you))

вс, 25 авг. 2019 г., 5:09 vincenthawke <notifications@github.com>:
