### ISSUE TITLE
Add a new value in the edit area

### ISSUE THREAD

**Issue by cavo789** [sergiodlopes/jquery-flexdatalist#22]
Hi Sergio,

Hope your fine.

I've tried to add a new value; not in the datalist, but in the selected value :

<img src="https://framapic.org/8NHpscmYIiwF/00oaI9xCm6Lu.png" width="400px" />

I've used the following code, based on one of your example : 
```html
<form class="col-md-4">
         <input 
		    id="language" 
			type='text' 
			placeholder='Programming language name' 
			class='flexdatalist' 
			data-min-length='1' 
			multiple='multiple' 
			value="PHP, Cobol, Java, Pascal"
			list='languages' />
      </form>
   
      <datalist id="languages">
         <option value="PHP">PHP</option>
         <option value="JavaScript">JavaScript</option>
         <option value="Cobol">Cobol</option>
         <option value="C#">C#</option>
         <option value="C++">C++</option>
         <option value="Java">Java</option>
         <option value="Pascal">Pascal</option>
         <option value="FORTRAN">FORTRAN</option>
         <option value="Lisp">Lisp</option>
         <option value="Swift">Swift</option>
      </datalist>
		 
      <button class="btn btn-default" data-value="C#">Add C#</button>
      <button class="btn btn-default" data-value="Lisp">Add Lisp</button>
      <button class="btn btn-default" data-value="Swift">Add Swift</button>

	  <script src="jquery-3.1.1.min.js"></script>
	  <script src="bootstrap.min.js"></script>
	  <script src="jquery.flexdatalist.js"></script>

      <script>
         $(document).ready(function() {
		 
            $('.btn').click(function(e) {
               e.preventDefault();
               $('#language').val($(this).data('value'));
            });
			
            $('#language').change(function(e) {
               alert($('#language').val());
            });
			
         });
      </script>
```

The `$('#language').val()` instruction reset the value to the new one.  
Is there somewhare a "add()" method to add a new value to the existing list ? 

Have a nice day.

**Comment by sergiodlopes** [comment]
Hi,

At the moment doesn't exist any way to add/append a value. You'll have to get current input value, add the value and set value:

`$('.btn').click(function(e) {
    e.preventDefault();
    var values = $('#language').val().split(',');
    values.push($(this).data('value'));
    $('#language').val(values.join(','));
 });`
This should work. :)

Cheers!

**Comment by cavo789** [comment]
I confirm, it works :+1: 

One thing : the onChange event is called so many times

```javascript
$('#language').change(function(e) {
   alert($('#language').val());
 });
```

(Note : I'm not blocked at this time, don't worry and, perhaps, add this feature for a future release ;-) )

**Comment by sergiodlopes** [comment]
> One thing : the onChange event is called so many times
I'll have a look at it. :)

> (Note : I'm not blocked at this time, don't worry and, perhaps, add this feature for a future release ;-) )
Yeah, I'll see if will be a requested feature. In this case I think the work around is quite clean, while implementing the feature in the code would require more lines of code to counter for all types of expected/possible inputs. I'll take a look if it's worth it. :)

Cheers!

**Comment by Krumator** [comment]
Worked for me Too :)

e.preventDefault();
    var values = $('#machines').val().split(',');
    values.push($(this).data('value'));
    $('#machines').val(values.join(','));
	
	var values2 = $('#brands').val().split(',');
    values2.push($(this).data('value'));
    $('#brands').val(values2.join(','));

SO Event If I call it from the DATABASE I dont loose the OLD values and can append new entered values to the input area.

Thanks a lot.

**Comment by sergiodlopes** [comment]
Hi,

Please check out release v2.0.0.
`$.flexdatalist('add', 'append this value')`
`$.flexdatalist('remove', 'remove this value')`

Thanks!
Sérgio
