### ISSUE TITLE
405 (Method Not Allowed)

### ISSUE THREAD

**Issue by Klerith** [sergiodlopes/jquery-flexdatalist#23]
Hi Sergio, 
Stunning plugin you have there, I have an issue trying to load data in json format, I am using the exact same data as you provide but I get this error 405 (Method Not Allowed).

I am pretty sure about the path of the data, also, I am running this on a localhost.
<img width="783" alt="captura de pantalla 2017-01-13 a las 07 56 08" src="https://cloud.githubusercontent.com/assets/3438503/21932347/caf18028-d965-11e6-8de0-dc9f2a5f85ad.png">

**Comment by sergiodlopes** [comment]
Hi Fernando,

That appears to be a problem in the server. Have you tried to chance the path to something else other than /data/?
It might be a security rule in your server to not allow "data" in urls.

Cheers!
Sérgio

**Comment by Klerith** [comment]
I am switching from node http-server to lite-server, and now I see something similar but this time is trying to perform a POST on what I thing should be a GET request.

![image](https://cloud.githubusercontent.com/assets/3438503/21932923/9fb90f68-d968-11e6-8794-8515a2d2ac0f.png)

**Comment by Klerith** [comment]
I just fixed my issue by changing the POST to GET on line 390 form the unmin version.

Sergio, I don't know if this is a bug, issue or something that need to me changed on the final version. Anyway, thank you for this amazing code


![image](https://cloud.githubusercontent.com/assets/3438503/21932986/f39cdd8a-d968-11e6-8efc-7a182fe4f4d6.png)

**Comment by sergiodlopes** [comment]
Yeah, technically, it should be a GET request, I agree.

I'll change it in my next release.

Thanks!

**Comment by sergiodlopes** [comment]
Hi,

On release 1.8.6 you can now change the type of request with option "requestType". Defaults to "post" to maintain compatibility with previous releases.

Cheers!
Sérgio
