### ISSUE TITLE
Same option selectable several times

### ISSUE THREAD

**Issue by LeFrach** [sergiodlopes/jquery-flexdatalist#24]
Hello Sergio :)

Thank You for your great plugin.

When I select an option from the list, this option is no longer available in the list.

Is it a way to add multiple times the same option into Input ? 

Thank you in advance.

`$('.flexdatalist').flexdatalist({
minLength: 3,
searchContain: true
}).on( "select:flexdatalist", function(event, input, text, options) {
/* Some code here */
});
`

**Comment by sergiodlopes** [comment]
Hi,

No problem. :)

Yes, now there is! Check out option 'allowDuplicateValues' on release 1.8.6.
Cheers!
Sérgio

**Comment by LeFrach** [comment]
Hi Sergio ! 
Seriously ? 
Thanks man !
