### ISSUE TITLE
Limit the amount of values you can select

### ISSUE THREAD

**Issue by JordanSayner** [sergiodlopes/jquery-flexdatalist#26]
I am trying to limit the amount of "tags" that can be added for a search field. But from looking at the docs and the source code, it doesn't seem like there is an option for this. 

Basically i want to limit the number of tags to 3/4.

Can anyone think of a way this can be achieved,

**Comment by sergiodlopes** [comment]
Hi,

Yeah, that's a good feature. I'll implement it.

Cheers!
Sérgio

**Comment by JordanSayner** [comment]
Awesome. Ill keep an eye out for it. Will it be a quick release? or something i will have to implement later down the line?

**Comment by sergiodlopes** [comment]
Hi,

Check out the option 'limitOfValues' in release 1.8.7

Cheers,
Sérgio

**Comment by JordanSayner** [comment]
Awesome, Good speedy work! Cheers man

**Comment by Aishawryazipare** [comment]
can you send the release 1.8.7 version link

**Comment by JordanSayner** [comment]
Here is the link for 1.8.7
https://github.com/sergiodlopes/jquery-flexdatalist/releases/tag/1.8.7

But their has been lots of newer versions released since this one. See all versions below.
https://github.com/sergiodlopes/jquery-flexdatalist/releases

**Comment by Aishawryazipare** [comment]
Thanks got it but i have two buttons. I want to check only one value is selected on the first button click & allow multiple select for another button click

**Comment by gelcows** [comment]
Buenas tardes, ua pregunta, existe una forma de validar un valor minimo de etiquetas?, es decir, si no se ha seleccionado un valor minimo de 3 o 4 elementos no permita continuar?.

Muchisimas gracias
