### ISSUE TITLE
Sticky Bar - Dropdown scrolls rather than sticks.

### ISSUE THREAD

**Issue by JordanSayner** [sergiodlopes/jquery-flexdatalist#27]
Hello,

I have a sticky bar along the top of the viewport using position fixed. The dropdown list loads fine, but then when i scroll, the dropdown list scrolls with the page, and not fixed to the bottom of the sticky header.

I have thought about the best way to overcome this and i can up with this idea.

Have an option that allows you to change weather its a fixed position, or an absolute position. I could just change the CSS to what i need, but if you have multiple instances of the dropdown in different places throughout a website, you might want both a fixed position and an absolute position. Also we will need to recalculate the top/left position depending on which positioning you choose.

I make it sound easy, but i know its not as easy as it sounds (for me anyway) as i have had play with the source code and couldn't figure it out.

If you have any other ideas on the best way to implement this, that would be great.

**Comment by sergiodlopes** [comment]
Hi,

Since the `position `property it's in the CSS, maybe you can use different classes depending on what position you might need:
`input.absolute-position {
      position: absolute;
}`
`input.fixed-position {
      position: fixed;
}`

`<input class="flexdatalist absolute-position" ...>`

Does this help in some way?

**Comment by sergiodlopes** [comment]
Hi,

Sorry, previous comment was incorrect. There's definitely a problem. You suggestion might work. I'll add an option to give more options.
While I don't release a option, I would suggest to use events to change the `.flexdatalist-results` list:
```
$('.flexdatalist').on('shown:flexdatalist.results', function () {
      $('.flexdatalist-results').addClass('position-fixed');
      // OR
      $('.flexdatalist-results').css('position', 'fixed');
});
```
This might give you some flexibility. :)

Cheers!

**Comment by JordanSayner** [comment]
Hi,

Sorry, the element i want to be position fixed is the actual dropdown list `<ul class="flexdatalist-results"...` , not the input. I've got the input field position fixed fine, its just the dropdown that I'm struggling with as the plugin dynamically generated the position, which currently positions itself as if it is an absolute position. where as i need it to position its self against the viewport not the document.

**Comment by sergiodlopes** [comment]
Yeah, sorry about my previous comment. I was wrong. But the last comment is a valid solution.

**Comment by JordanSayner** [comment]
Hi, 

Sorry i didn't see your updated answer, i hadn't refreshed since i read it originally, I will have a play with your snippet and see what i can do.

Cheers for your help.
