### ISSUE TITLE
Show all results on focus is buggy on mobile

### ISSUE THREAD

**Issue by benjamin-thomas** [sergiodlopes/jquery-flexdatalist#29]
On mobile safari (and hence chrome too), you have to focus, press `OK` and the keyboard, and focus again to get the dropdown.

**Comment by sergiodlopes** [comment]
Hi,

I'll have to research better the possible problem. There's something not quite right on multiple values field.

I'll check it out.

**Comment by sergiodlopes** [comment]
Hi,

Can you please check release 1.9.0 if it solves your issue?

Thanks!

**Comment by benjamin-thomas** [comment]
Hello @sergiodlopes 

The feature works correctly on mobile safari now (IOS 10.2.1), but is still buggy on mobile chrome. The pull down appears properly sometimes, and some other times nothing happens, in a seemingly random way (after a page reload each time).

I tested it in a private tab just in case, but the behavior is the same.

It feels like another event is triggered, bypassing the original onfocus, although I haven't dug further, dev tools being unavailable on that platform.

By the way, I wasn't quite clear about this, but I tested the feature from your site directly: http://projects.sergiodinislopes.pt/flexdatalist/

**Comment by sergiodlopes** [comment]
Hi,

I'l check it out. Thanks for helping testing it.

**Comment by sergiodlopes** [comment]
Hi,

Please check out release v2.0.0, if the issue persists, please, reopen this issue.

Thanks!
Sérgio

**Comment by benjamin-thomas** [comment]
Hello @sergiodlopes,

I can confirm this bug no longer exists on both browsers.

Well done!
