### ISSUE TITLE
Customize local search

### ISSUE THREAD

**Issue by benjamin-thomas** [sergiodlopes/jquery-flexdatalist#30]
Your plugin looks great!

Would you consider allowing different search strategies?

As a reference, I find the search behavior of [selectize](http://selectize.github.io/selectize.js/) really useful.

![image](https://cloud.githubusercontent.com/assets/1557738/22367745/77297634-e483-11e6-96ce-48d02b481913.png)

Any thoughts?

**Comment by sergiodlopes** [comment]
Hi,

Good suggestion. Thanks. I'll add that in my next release.

Cheers!

**Comment by sergiodlopes** [comment]
Hi,

Check out release 1.9.0's option "searchByWord".

Cheers,
Sérgio

**Comment by benjamin-thomas** [comment]
Congrats!!

Can't wait to play with your plugin some more!
