### ISSUE TITLE
custom post variable

### ISSUE THREAD

**Issue by cyberzilla** [sergiodlopes/jquery-flexdatalist#32]
how to add custom post variable for remote url?

**Comment by sergiodlopes** [comment]
Hi,

Use option "params" to set an object with the data you would like to send with the request.

Sérgio

**Comment by cyberzilla** [comment]
cool plugins, thanks

**Comment by cyberzilla** [comment]
how to define new param in html5 element?

i have try data-params="act:'loadUrl'", but not work

**Comment by sergiodlopes** [comment]
Hi,

`data-params='{"act":"loadUrl"}'`
