### ISSUE TITLE
all hidden element duplicate and show if i reset form

### ISSUE THREAD

**Issue by cyberzilla** [sergiodlopes/jquery-flexdatalist#33]
all hidden element duplicate and show with id "...-flexdatalist"

i am reset/clear form field with function
```
function clearForm(frm){
   $("#"+frm).find('input:text, input:hidden ,input:password, input:file, textarea').val('');
}
```
how to fix this?

**Comment by sergiodlopes** [comment]
Hi,

Please try it now with release 1.9.0.
Hope it fixes the problem for you.

Cheers,
Sérgio
