### ISSUE TITLE
Issue during initialization

### ISSUE THREAD

**Issue by RollinLedru** [sergiodlopes/jquery-flexdatalist#34]
Hi Sergio and thanks for your plugin !
English is not my primary language so forgive my mistakes. I hope i will be clear enough.

I configure a custom flexdatalist to have multiple values and authorize values not from the data (selectionRequired=false). The datalist is read in a database thanks to a call to an url which send back a json object.  That works great.

In my application, i have that screen : 

![image](https://cloud.githubusercontent.com/assets/25688599/22830420/c607d362-efa6-11e6-8e6d-08a645597991.png)

In the case of the previous screen, "{ResourceName}", "{Country}" and "{Status}" are values which are in the datalist. "Value1NotInSelection" and "Value2NotInSelection" are not. 

When i click Save Button, the string "{ResourceName},{Country},{Status},Value1NotInSelection,
Value2NotInSelection" (corresponding to the flexdatalist value is recorded in my database.

When i want to edit this record, i do this
![image](https://cloud.githubusercontent.com/assets/25688599/22830773/07bee998-efa8-11e6-99a6-50bbffcb583d.png)

But, only the values which are in the datalist appear in the flexdatalist : 

![image](https://cloud.githubusercontent.com/assets/25688599/22830193/e16ba17a-efa5-11e6-8609-8046bff6dc0f.png)

I tried a lot of things but i could not succeed in having all the values (including values not in the datalist) at the initialization of the plugin.

I hope i'm clear enough
Thanks
Edouard

**Comment by sergiodlopes** [comment]
Hi,

Yeah, I understood the problem. I'll look at it.

Cheers!
Sérgio

**Comment by sergiodlopes** [comment]
Hi,

Please check out release v2.0.0, if the isse persists, please, reopen it.

Thanks!
Sérgio
