### ISSUE TITLE
type property can't be changed using jQuery > v1.8.3

### ISSUE THREAD

**Issue by tokutoku3** [sergiodlopes/jquery-flexdatalist#35]
Hello Sergio, 

I've tried jquery-flexdatalist in my project.
So, this error occurred because `$.attr()` can't be change type property. (> v1.8.3)

<img width="610" alt="2017-02-09 14 43 40" src="https://cloud.githubusercontent.com/assets/1570366/22868887/0546a9b6-f1de-11e6-9443-5e2ad21fcb11.png">

How about changing it as follows? 
(Unless you use `$.attr()` for a special reason)
```js
$this.addClass('flexdatalist flexdatalist-set').prop('type', 'hidden');
```
https://github.com/sergiodlopes/jquery-flexdatalist/blob/master/jquery.flexdatalist.js#L207

Great work!

---

This is `$.attr()` and `$.prop()` example.

jQuery v1.8.3 attr sample  
http://codepen.io/tokutoku3/pen/PWXELm
jQuery v1.9.1 attr sample  
http://codepen.io/tokutoku3/pen/apPEMg

**Comment by sergiodlopes** [comment]
Hi,

Thanks for the heads up!
Hopefully it's fixed in v1.9.1. Please check it out.

Cheers!
Sérgio
