### ISSUE TITLE
searchByWord : a couple of bugs

### ISSUE THREAD

**Issue by benjamin-thomas** [sergiodlopes/jquery-flexdatalist#36]
Hello @sergiodlopes.

I'm loving your project so far. Congrats again on the `searchByWord` feature.

I found a couple of bugs however (v. 1.9.1):

1. When pressing the space bar, the current results are lost, i.e.

![image](https://cloud.githubusercontent.com/assets/1557738/23009638/77bc26fc-f417-11e6-806a-2e8bb84bbb2d.png)

2. On the next keypress after the space bar, some highlight code gets into the output:
![image](https://cloud.githubusercontent.com/assets/1557738/23009696/ad6125b4-f417-11e6-9bc8-16aa8414b536.png)

**Comment by sergiodlopes** [comment]
Hi,

Thanks for bringing to my attention. Check out release v1.9.2.

Cheers,
Sérgio

**Comment by benjamin-thomas** [comment]
Great! Would you consider publishing your releases to bower and/or npm ?

It would make updating easier.

**Comment by sergiodlopes** [comment]
Hi,

Sure, I'll Starr doing that more rigourously.

Cheers,
Sérgio
