### ISSUE TITLE
Default Value and New value

### ISSUE THREAD

**Issue by andering** [sergiodlopes/jquery-flexdatalist#37]
Hello, thank you for great job with this module.
I got two questions:

1. how do i set default value  if using for editing some existing record ? 
If i simply set value="<value>" , event "change:flexdatalist" is being triggered 3 times while loading,
so if i have some duplicity control bind to the event it trigger my modal windows.

2. can i use the flexdatalist input to be used to  add new values ?

Thank you.

**Comment by sergiodlopes** [comment]
Hi,

1. The default value must be in the same format as the one that flexdatalist is configured to send. Taking the examples in documentation with the countries, if I have a field that sends the country ID, the default value to set the input must be an/the ID. About the multiple triggers, sorry, try the release 1.9.2 and check it out, in the future I'll do a refactoring to the plugin. It has grown substantially and needs some optimizations.

2. Add new value like a normal text input? Or add to the data pool after init?

**Comment by Mordef** [comment]
Hi, default values works fine with 1.9.2
My data looks like:
`[{id:1,name:"tagone"},{id:2,name:"tagtwo"}]`

HTML:
`<input type="text" id="tags" name="msp-keywords" value="1,2" />`

**Comment by andering** [comment]
@Mordef thank you, will try if it triggers change:flexdatalist event while init
@sergiodlopes like a normal text input, but i figured out,
if there is no option in pool value  equal  ""  so when value equal "" i'll take value from #element-flexdatalist

Thank you.

**Comment by jonhue** [comment]
@sergiodlopes I've got a similar problem. When I try to set default values for my inputs with remote data, they just reset when I initialize flexdatalist. I am using ID's as values too.

**Comment by andreasrosenthal** [comment]
@sergiodlopes @jonhue Same here, it one case it's working, in all other cases not. Haven't found any differences. Setting the val() "manually" to something in the code doesn't work either. Please advice, this is quite important for edit scenarios. Thanks for the great component!

**Comment by andreasrosenthal** [comment]
@sergiodlopes @jonhue Was able to fix it by casting the value to a string in my API.

**Comment by jonhue** [comment]
@andreasrosenthal @sergiodlopes 

Hmm... this is still not working for me. Neither the methods `val()` / `flexdatalist()` nor setting the `value` attribute.

**Comment by jonhue** [comment]
@andreasrosenthal Are you using a remote JSON file?

**Comment by jonhue** [comment]
@andreasrosenthal @sergiodlopes 

That's weird, this is what I do:

```haml
= component 'myg/form-field', as: :input, attribute: :quantity_id, class_name: "calculation[measurements_attributes][#{index}]", input_html: { required: true, placeholder: t('d.quantity'), class: 'select flexdatalist', value: local_assigns[:measurement]&.quantity_id.to_s, data: { units: "#calculation_measurements_attributes__#{index}___unit_of_measurement_id", data: '/app/quantities.json?all=true&locale=' + I18n.locale.to_s, search_in: ['sym', 'name'], text_property: 'name', visible_properties: ['sym', 'name'], selection_required: 'true', value_property: 'id', min_length: '0' } }
```

```js
require('jquery-flexdatalist/jquery.flexdatalist');
```

It does initialize jquery-flexdatalist correctly, but it overwrites the value.

**Comment by rfenaux** [comment]
Hello @jonhue , did you manage to find a fix ?
I'm stuck with the same problem -> default value is set for 1/100 of sec then reset

I've been looking everywhere I could think of and ... no idea 😢

**Comment by jonhue** [comment]
No, wasn't able to.
