### ISSUE TITLE
Default value 'multiple'

### ISSUE THREAD

**Issue by Mordef** [sergiodlopes/jquery-flexdatalist#38]
Hello Sergio,

great job, thanks a lot.

Can you please change a small thing?

`multiple: $this.attr('multiple'),`
to
`multiple: false,`

So the HTML-Input element dont need the attribute "multiple".

Thank you.

**Comment by sergiodlopes** [comment]
hi,

Sure, I'll do that in my next release!

Cheers,
Sérgio

**Comment by Mordef** [comment]
Great, thanks
