### ISSUE TITLE
Get all ID's

### ISSUE THREAD

**Issue by Mordef** [sergiodlopes/jquery-flexdatalist#39]
Hi Sergio,

i try to find all selected ID's but i get only the Text.
Any way to get all selected ID's?

I made some changes for me.
New default option:
`dataValues : [],`

Line 862-865:
```
                var l = _options.dataValues.length;
                while(l--) {
                	$li.attr('data-' + _options.dataValues[l],val[_options.dataValues[l]] );
                }
```

Now i can decide wich values i want to have as new attributes in the LI

**Comment by sergiodlopes** [comment]
Hi,

Get the ID's from...?

**Comment by Mordef** [comment]
Hi,

from the data avaible in the list:
`[[id: 1, name: 'text'], [id: 2, name': 'text2']]`

Atm i can only become the text i see when i write something, but i need the assigned ID.
With the small code above i added 'data-id' to the LI-Element so i can access that value.

(sry for my bad english:) )

**Comment by sergiodlopes** [comment]
Hi,

Hmm... maybe set the `valueProperty `option to `id`.

**Comment by sergiodlopes** [comment]
Hi,

Please check out release v2.0.0, if the issue persists, please, reopen this issue.

Thanks!
Sérgio
