### ISSUE TITLE
Add value to the input

### ISSUE THREAD

**Issue by vugarrio** [sergiodlopes/jquery-flexdatalist#4]
Hello, great job.

Is it possible to add any value to the input? Something like $('.flexdatalist').val('Hello'). 

Thank you in advance.

**Comment by sergiodlopes** [comment]
Hello. Thank you. Glad that you also find it useful.

At the moment there are some limitations on the plugin, to programmatically change the value after init.
Depends on what you're trying to do. You need to had the value before or after init?

**Comment by vugarrio** [comment]
Thanks for answering,

I would need it after init.

I have two input (flexdatalist) reading the same json. I need the second input to acualice with some json data selected in the first input.
 
```

 var fNPLogin = $('#formN input[name="login"]').flexdatalist({
		    	searchContain: true,	
		    	focusFirstResult: true,
		        selectionRequired: false,
		        minLength: 1,
		        searchIn: 'login',
		        data: 'data/users.json',
		        visibleProperties: ["login"]
		    });

 var fNICodEmp = $('#formN input[name="cod_emp"]').flexdatalist({
		    	searchContain: true,	
		    	focusFirstResult: true,
		    	selectionRequired: false,
		    	minLength: 1,
		    	searchIn: 'cod_empresa',
		    	data: 'data/users.json',
		    	visibleProperties: ["cod_empresa"]
		});


 $(fNILogin).on('select:flexdatalist', function(e, itemObject, options) {
		    	
		    	/*  I need this  --->   */   $(fNICodEmp).val(itemObject.cod_empresa);

		    	logger.info("...Selected: " + JSON.stringify(itemObject));
		})
```

Thank you in advance.

**Comment by sergiodlopes** [comment]
Yes, it will set and send whatever value you set on the input. From the user/UI perspective, probably won't give the correct feedback to the user about the value that's currently set.

What value does the input send from the object properties?

**Comment by vugarrio** [comment]
They would have to send the item selected json.  Show the data set to 'visibleProperties'.

Example:   {"cod_empresa": "20079", "login": "sampe", "email": null, "name": "Javier"}

**Comment by sergiodlopes** [comment]
The `visibleProperties` is only for visible properties in search results (dropdown) (yeah, its quite ambiguous the name, I'll change that).

I think that one way of doing what you want, would be to add JSON string as value and reset flexdatalist with `off()`:
 ```
var fNICodEmpConfig ={
                searchContain: true,    
                focusFirstResult: true,
                selectionRequired: false,
                minLength: 1,
                searchIn: 'cod_empresa',
                data: 'data/users.json',
                visibleProperties: ["cod_empresa"]
        };
 $(fNILogin).on('select:flexdatalist', function(e, itemObject, options) {
                $(fNICodEmp).val(JSON.stringify(itemObject)).off().flexdatalist(fNICodEmpConfig);

                logger.info("...Selected: " + JSON.stringify(itemObject));
        })
```
Flexdatalist doesn't have a reset/destroy method yet. I'll add that and make some improvements for more flexibility (pun not intended... hehe).

**Comment by vugarrio** [comment]
Thank you very much for your help.

**Comment by sergiodlopes** [comment]
No problem. It worked?
