### ISSUE TITLE
focus()

### ISSUE THREAD

**Issue by andreasrosenthal** [sergiodlopes/jquery-flexdatalist#41]
Can you please advice on how to focus on a search field? 

I assume flexdatalist generates a new input field suffixed "-flexdatalist" which carries the text input, while the original input field is storing the selected value. 

Trying to focus() on that field $("#somfield-flexdatalist").focus(); doesn't work (without any errors raised).

Any hints please? 

Thanks in advance!

**Comment by Mordef** [comment]
Hi,

found no event for this.
You can use this:

```
	window.setTimeout(function(){setFocus('keys');},100);
	function setFocus(elId) {
		if ($('#' + elId).next().find('input').length===1) {
			$('#' + elId).next().find('input').focus();
			return;
		}
		window.setTimeout(function(){setFocus(elId);},100);
	}

```
