### ISSUE TITLE
Can't listen to flexdatalist events when I have multiple datalists in a form

### ISSUE THREAD

**Issue by steevehook** [sergiodlopes/jquery-flexdatalist#42]
// The first event will work, yet listening to the second won't

$("#answer-all-answers-input").on("shown:flexdatalist.results", function (event, results) {
            $(".flexdatalist-results").css("border", "1px solid rgb(204, 204, 204)");
            $(".flexdatalist-results").css("border-top", "none");
        });

        $("#answer-all-messages-input-flexdatalist").on("shown:flexdatalist.results", function (event, results) {
            console.log("messages");
            $(".flexdatalist-results").css("border", "1px solid rgb(204, 204, 204)");
            $(".flexdatalist-results").css("border-top", "none");
        });

**Comment by sergiodlopes** [comment]
Hi,

Please check out release v2.0.0, if the issue persists, please, reopen this issue.

Thanks!
Sérgio
