### ISSUE TITLE
Change the value of different field based on the autocomplete selection chosen

### ISSUE THREAD

**Issue by zeckdude** [sergiodlopes/jquery-flexdatalist#43]
I have JSON data that includes 3 related properties. 

```
[
  {
    "organization": "McDonalds",
    "city": "Las Vegas",
    "state": "NV"
  }
]
```

One property is for the input field on which `flexdatalist` is initialized on (In my example it is `organization`). When an autocomplete selection is chosen, the `organization` field is populated perfectly. At this point, I would like to somehow specify two other form fields and have those form fields be populated with the other two related properties. Is that possible via flexdatalist?

**Comment by sergiodlopes** [comment]
Hi,

If I understood it correctly, yes, it's possible. for example, if on selection you would like to have the format `Organization, City - State` populated in the field, just set the `textProperty` to `{organization}, {city} - {state}`. Selecting McDonalds as the organization, it would appear in the input as `McDonalds, Las Vegas - NV`.

Cheers,
´Sérgio

**Comment by zeckdude** [comment]
Hi,

No, I don't want the organization, city, and state in the same field. I want the organization in one input field, the city in a second input field, and the state in a third dropdown field.

**Comment by sergiodlopes** [comment]
Hi,

It appears that `input#city` is losing the preset options. The plugin needs some serious refactoring. I have two suggestions:

1. Try release v1.9.3, it should fix some problems and hopefully yours
2. Do you need to have 2 inputs? It appears to me that all info is already in `organizations.json`. So if I pick organization `McDonalds` it would send JSON string:
```
{
    "organization": "McDonalds",
    "city": "Las Vegas",
    "state": "NV"
  }
```
Sending all the info you need on the server side (IMHO).

Does this help in some way?
