### ISSUE TITLE
Text persist even when the option "selectionRequired" is turned on

### ISSUE THREAD

**Issue by Rolige** [sergiodlopes/jquery-flexdatalist#45]
The text persist only in the input cloned, the text typed is not copied to the master input, which is well, but is confused when you left (blur) the input and text stay there.

PD. Congratulations for the plugin, is the best I found after an exhaustive search.

**Comment by sergiodlopes** [comment]
Hi,

I'll improve the input feedback (that nothing was selected) on blur. Thanks!

Cheers,
Sérgio

**Comment by Rolige** [comment]
Nice, thanks for your attention.
