### ISSUE TITLE
default values (Multiple): search by id , not perfect match

### ISSUE THREAD

**Issue by kialala** [sergiodlopes/jquery-flexdatalist#46]
Hi,

A big shoutout for your hard work!

I'm having a weird bug with flexdatalsit (latest release 1.9.3), it seems like default values are run by a "substring" match rather than a perfect one...

I do have default values fed on the plugin. The json source data is structured this way:

```JSON
[ { "id": "1", "capital": "Madrid", "country": "Spain" }, 
 { "id": "2", "capital": "Buenos Aires", "country": "Argentina" },
 { "id": "20", "capital": "Kuala Lumpur", "country": "Malaysia" },
 { "id": "10", "capital": "Ottawa", "country": "Canada" } ]
}
```
I would like to have id=1 and id=2 as default values, I tried this first:
```javascript
		$('.flexdatalist').val('1,2').flexdatalist({
			     minLength: 0,
			     valueProperty: 'id',
                             textProperty: '{country}, {capital}',
			     selectionRequired: true,
     			     visibleProperties: ["capital","id","country"],
			     searchIn: 'country',
			     data: 'c.php',
		});
```
 and then I opted for the more "conventional" method:

```html
	  	<input type='text'
		      placeholder='Choose the country'
		       class='flexdatalist'
		       multiple='multiple'
                       value='1,2'
			       >
```
Both methods would display ALL instances where id contains 1 or 2 INCLUDING id=10 id=20...

![capture](https://cloud.githubusercontent.com/assets/20996699/24001688/936c49a4-0a3d-11e7-8966-0de416271470.PNG)

Could you look into this, I would like to have id searched on a "perfect match" logic.

Thanks

**Comment by sergiodlopes** [comment]
Hi,

Check out release v1.9.4. It should be fixed.

Cheers!
