### ISSUE TITLE
IE placeholder problem

### ISSUE THREAD

**Issue by JordanSayner** [sergiodlopes/jquery-flexdatalist#47]
Hello,

When using this script, i seem to be getting an error in IE that is caused by the Placeholder on the input field.

I was using V1.8.7 but also updated to V1.9.4 but still getting the same error, slightly confused as the demos on your website are working properly.

My code is as below

```
            $('.search__location-field').flexdatalist({
                requestType: 'get',
                minLength: 0,
                visibleProperties: ["name", "amountOfVillas", "location"],
                searchIn: 'name',
                data: '/autocomplete.json',
                groupBy: 'category',
                selectionRequired: true,
                toggleSelected: true,
                maxShownResults: 5,
                limitOfValues: 1,
                searchContain: true,
                valueProperty: '*',
            });
```

```
<input type='text' placeholder='Where do you want to go?' class='search__location-field' name='search__location-select' multiple='multiple' id="tbx_Search_Location">
```

The error I'm getting is when i click on the input field, and then select one of the items from the dropdown

```
Line 912:                         value = JSON.parse(value);
```

When i put a breakpoint on that line in dev tools, the value is showing the content that is within my placeholder (`Where do you want to go?`).

When i remove the placeholder it works fine, But i need the placeholder to be there.

Any ideas what could be causing this issue?

The problem is only on IE 11 and 10, 9 works due to no support of the placeholder attribute.

**Comment by sergiodlopes** [comment]
Hi,

Hmm... don't see what could be causing that problem. I think the plugin doesn't touch the `placeholder`.
Could it be when cloning the element?

**Comment by sergiodlopes** [comment]
Hi,

Please check out release v2.0.0, if the issue persists, please, reopen this issue.

Thanks!
Sérgio
