### ISSUE TITLE
Text Pointer jump to end of the string

### ISSUE THREAD

**Issue by NyoCon** [sergiodlopes/jquery-flexdatalist#5]
Hey,

if i set the option selectionRequired to false, the text pointer always jump to the end of the string if i start writing somewhere else except at the end.

For example: I want to write the Word "Hello" but instead i wrote "Hlo" so i jumped back after the "H" to write the missing Characters "el". After writing the e the pointer is jumping to the end of the field.

It seems there is no possibility to change that with the given options.

Would be nice to get a possibility to avoid that problem.

Greetings

**Comment by NyoCon** [comment]
I found a workaround

jquery.flexdatalist.js - Line 237
`if (!_options.multiple) {
     if (!_options.selectionRequired) {
         $this._value(val);
     } else if (val.length === 0 || !$this._selected()) {
         $this._value('');
     }
}`

Remove "$this._value(val);" and it works.

**Comment by sergiodlopes** [comment]
Hey,

Thanks for the heads up!

I was at the moment checking that line and what is its purpose. Hope that fix works for you.
I'll release a fix today.

Greetings

**Comment by NyoCon** [comment]
Thanks for the quick reply. Hope to see your fix soon :) 
And nice work with this plugin!

**Comment by sergiodlopes** [comment]
No problem. Thanks for bringing it to my attention.
The fix is on the 1.4.4 release.

Thanks!

**Comment by NyoCon** [comment]
Hey,

today i tried your new version and it seems that the bug still exists.
You can test it yourself using the  first example on your project page.

Greetings

**Comment by sergiodlopes** [comment]
Hey,

Damn. What browser and OS you're using?

**Comment by NyoCon** [comment]
I'm on Linux Mint 18 using Google Chrome.
I also tested Firefox and it seems to work fine.

So i asked my colleague to test it too and he ran into the same problem.

**Comment by NyoCon** [comment]
We tried some more Browsers:

Works in Firefox and Microsoft Edge 13 & 14.
Doesn't work in Google Chrome, Internet Explorer 11 and Safari.

**Comment by sergiodlopes** [comment]
Thanks for your help. 

I'll work on a fix today. Your feedback on testing across browsers will be of value. Thanks!

**Comment by NyoCon** [comment]
One more thing:
It's not possible to mark the text with CTRL + A combination.

**Comment by sergiodlopes** [comment]
Hey,

Can you confirm that on the demo page is working ok? Thanks!

**Comment by NyoCon** [comment]
Hey,

i tested it on the first example and there bug is still there :/

**Comment by sergiodlopes** [comment]
I was trying to solve the wrong problem. Sorry, long day...

When you can, please test it again on the demo page.

Thanks!

**Comment by NyoCon** [comment]
Yes now it works  :D 
Great work, thank you very much.

There is one more thing (not that important) that you might want to know.
Somehow this plugin is firing an ajax request if the data list is empty. (Maybe to fill the list with new entries)
I'm using an array to set the data so there is no need for this request. And there is a little chance that the data array become empty. I'm also not using the url option.
I'm not sure but that might be bug also, isn't it?

**Comment by sergiodlopes** [comment]
Great! :)
No problem, thank you for testing it.

Yeah, it seems a bug. I'll take a look at it before releasing the version with the new fixes.
