### ISSUE TITLE
change: event when there are multiple values

### ISSUE THREAD

**Issue by cavo789** [sergiodlopes/jquery-flexdatalist#51]
Hello Sergio

I can't find on the net any documentation so, excuse me if the question seems trivial : how can I detect that the user remove values ?

In your [samples](http://projects.sergiodinislopes.pt/flexdatalist/), you've one called "TOGGLE VALUE(S) ON CLICK/TAP" with already two values and the small "x" button to remove them one by one.

By removing "Nicaragua" f.i., the list of IDs just below still mention his ID. Even by removing Portugal, IDs stays.

How can we implement a function that will be called when the user remove an items ?

(my real worl need : by removing a value, I need to refresh my treeview and by removing all values, my treeview should display everything).

Thanks Sergio !

**Comment by sergiodlopes** [comment]
Hi,

Please check out release v2.0.0, if the bug persists, please, reopen this issue.

Thanks!
Sérgio
