### ISSUE TITLE
Comma not working on android mobiles

### ISSUE THREAD

**Issue by Sesu002** [sergiodlopes/jquery-flexdatalist#56]
Hi,
     If i enter non predefined value and click comma means its not working. Its taking comma also a string. enter is working well. Desktop browsers comma and enter working. mobile browsers comma not working.

**Comment by sergiodlopes** [comment]
Hi,

I'll check out that problem.

Thanks!
Sérgio

**Comment by sergiodlopes** [comment]
Hi,

Please check out release v2.0.0, if the bug persists, please, reopen this issue.

Thanks!
Sérgio

**Comment by Sesu002** [comment]
Hi. Still the bug is there. Not yet solved. I tried in my Android with chrome browser. If i enter random string and enter comma means still its taking comma as a string. Its not taking comma as a divider.

**Comment by sergiodlopes** [comment]
Hi,

Unfortunately is related with not being able to detect key codes in mobile browsers (at least in Android's Chrome).

Since pressing `enter` key works, I would recommend suggesting your website users/visitors to use it instead of `comma` to add value.

Sérgio

**Comment by sergiodlopes** [comment]
Updated documentation to incentivize de use of `enter` instead of comma to add values.

Thanks!

Sérgio
