### ISSUE TITLE
Flexdatalist loading spinner

### ISSUE THREAD

**Issue by recruitname** [sergiodlopes/jquery-flexdatalist#58]
I couldn't find it in flexdatalist, is there spinner for autocomplete ?

for example like this: http://cdn.rawgit.com/salmanarshad2000/demos/v1.0.0/jquery-ui-autocomplete/custom-html-in-dropdown.html

if you type `PHP` you will see spinner right of the input, I want to add inside of my input is that possible with flexdatalist ?

**Comment by sergiodlopes** [comment]
Hi,

Yes, it's possible. You'll need to implement the spinner yourself using the available events.
Check out `before:flexdatalist.data` and `after:flexdatalist.data` in [http://projects.sergiodinislopes.pt/flexdatalist/](http://projects.sergiodinislopes.pt/flexdatalist/)

Cheers!
Sérgio
