### ISSUE TITLE
Update data for existing instance

### ISSUE THREAD

**Issue by NyoCon** [sergiodlopes/jquery-flexdatalist#6]
Hey,

it's me again.
This is not a bug but a nice feature i think.

At the moment you have to pass the data by creating a new flexdatalist. To update this data or set new data you have to use the delete function and recreate a new flexdatalist with the new object.

It would be a nice feature to update the data on the fly without destroying and creating a new list.
The problem with destroying is, if the list gets destroied while typing in an input field you lose your focus to this field.

An "updateData"-like Method would be a nice feature.

Greetings

P.S.: In my example i delete entries which are already in an input field to avoid duplicates. But if i change my mind and remove the string i need to add it again to the list. This all happens on keyup event means while typing in the input field.

**Comment by sergiodlopes** [comment]
Hey,

Yes it is a nice feature. :)
I realized what you were going to be needing that when you commented the bug where data and url would be empty. For sure you would set the data later on after init... hehe :)

I will for sure implement that feature.

Thanks!

**Comment by NyoCon** [comment]
Nice, thanks man!
Pleased to see this feature soon :)

**Comment by NyoCon** [comment]
Hey, I just wanted to ask when you plan to implement this?

Greetings

**Comment by sergiodlopes** [comment]
Hey,

I'll try to implement it next weekend. :)

**Comment by sergiodlopes** [comment]
Hey,

Sorry for taking so long. Check out version 1.5.0 ;)

If you find any bugs in the new release, please, let me know!

Thanks!

Sérgio

**Comment by NyoCon** [comment]
Hey, thank you for this update.

I need to do some refactoring because selected values from the list won't appear in the input field.
I don't know what exactly have changed but i will take a look later this week.

Greetings

**Comment by sergiodlopes** [comment]
Hey!

I've just fixed that issue. Yeah, it wasn't processing a given input value on init.
Check the release 1.5.2 if it fixes it.

Greetings

**Comment by NyoCon** [comment]
Hey,
it's me again. I had a new project but now i can review this issue.
I build a simple test case with a html file which only includes the input field and the css and js files.

`<input type="text" id="selection">`

My JS looks like this:

`$('#selection').flexdatalist({
            minLength: 0,
            searchIn: 'name',
            data: [
                {
                    "id": 1,
                    "name": "Test1"
                },
                {
                    "id": 2,
                    "name": "Test2"
                },
                {
                    "id": 3,
                    "name": "Test3"
                }
            ]
        })`

So far so good. Now i wan't to change the data by typing in the field. So i added:

`$('body').on('change', '#selection', function (e) {
            e.preventDefault();

            $('#selection').flexdatalist({
                data: [
                    {
                        "id": 1,
                        "name": "1Test"
                    },
                    {
                        "id": 2,
                        "name": "2Test"
                    },
                    {
                        "id": 3,
                        "name": "3Test"
                    }
                ]
            })
        });`

But it doesn't change the data.

**Comment by NyoCon** [comment]
Hey,

that works perfectly :+1: 
Didn't see this in the documentation ^^

Thanks for the great work!

**Comment by sergiodlopes** [comment]
Great! :)

Yeah, I'll improve the documentation. Thanks!

No problem, good to know that is useful to your work.
