### ISSUE TITLE
how to post keyword with other name and how to post more data

### ISSUE THREAD

**Issue by peon501** [sergiodlopes/jquery-flexdatalist#60]
how to post keyword with other name and how to post more data?

I have large data in php so iam using filters by where in php
so i need to post with ajax more data.
I need to change name of keyword to q
and add more data fields like category

**Comment by sergiodlopes** [comment]
Hi,

The name of the keywork it's not possible to change in config. I'll add that option.

Thanks!
Sérgio

**Comment by sergiodlopes** [comment]
Hi,

Check out v2.0.0, in particular, option `keywordParamName`.

Thanks!
Sérgio
