### ISSUE TITLE
Results mismatch with toggleSelected

### ISSUE THREAD

**Issue by pdrlps** [sergiodlopes/jquery-flexdatalist#61]
Great job on the plugin!

I'm having some issues with the toggleSelected option. Here's the workflow

1. search item A
2. select item A
3. toggle item A, it's now deselected
4. search item A
5. select item A
6. remove item A, remove item A (the deselected one)
7. search item A... no results

![flexdatalist_issue](https://cloud.githubusercontent.com/assets/210283/26067448/38a29d78-3992-11e7-9f4a-e5ff5b95318f.gif)

**Comment by sergiodlopes** [comment]
Hi,

Thank you for your feedback. I'm working on v2.0, doing some refactoring on the plugin.

Cheers!
Sérgio

**Comment by sergiodlopes** [comment]
Hi,

Please check out release v2.0.0, if the bug persists, please, reopen this issue.

Thanks!
Sérgio
