### ISSUE TITLE
Flexdatalist resizing issue

### ISSUE THREAD

**Issue by recruitname** [sergiodlopes/jquery-flexdatalist#62]
I have three autocomplete on my page and three of them in a same div side by side.and after result data if I resize the page my results is overlapping or something like that as you see on image

When I type a something
![flex_open_1](https://cloud.githubusercontent.com/assets/25980843/26092676/fa2b8b0c-3a1a-11e7-91e2-2f82141e7992.jpg)

and after I resize

![flex_open_2](https://cloud.githubusercontent.com/assets/25980843/26092682/fd98ffae-3a1a-11e7-83f3-21f1721dedad.jpg)

but if I use only one autocomplete than I don't get any issue and my last autocomplete is not overlapping and only it's working as expect

my js code

```
$('.input').flexdatalist({
    requestType: "POST",
    searchDisabled: true,
    searchByWord: true,
    searchContain: true,
    textProperty: '{name}',
    valueProperty: 'name',
    maxShownResults: 50,
    focusFirstResult: true,
    selectionRequired: true,
    groupBy: 'category',
    visibleProperties: ["name", "category", "description", "font"],
    searchIn: true,
    url: '/ajax/SearchOtel',
});

```

```
$('.input2').flexdatalist({
    requestType: "POST",
    searchDisabled: true,
    searchContain: true,
    textProperty: '{name}',
    valueProperty: 'id',
    groupBy: 'category',
    maxShownResults: 50,
    focusFirstResult: true,
    selectionRequired: true,
    visibleProperties: ["name", "category", "description", "font"],
    searchIn: true,
    url: '/ajax/SearchTur',
});
```

```
$('.input3').flexdatalist({
    requestType: "POST",
    searchDisabled: true,
    searchContain: false,
    textProperty: '{name}',
    valueProperty: 'address',
    selectionRequired: true,
    visibleProperties: ["icon", "name"],
    searchIn: ["name", "icon"],
    url: '/ajax/SearchTatilRehberi',
});
```

and my all autocomplete class and parents of autocomplete is different they are not using same css class thanks.

I want to give you a live example but I have no my own host and codepen is not supporting json file sorry

edit: I added alternate link [please click here to see demo](http://yurtici.anitur.com.tr/musteri/ingoing/2017/htm/flex/)

**Comment by sergiodlopes** [comment]
Hi,

Thanks! I'll fix it!

Cheers!
Sérgio

**Comment by recruitname** [comment]
it confuses from its various this variables in the _position function and how can we fix it for now ? I need to fix it thank you

**Comment by sergiodlopes** [comment]
Hi,

Check out [https://github.com/sergiodlopes/jquery-flexdatalist/releases/tag/1.9.5](https://github.com/sergiodlopes/jquery-flexdatalist/releases/tag/1.9.5).

Cheers!
Sérgio

**Comment by recruitname** [comment]
yes I change code and get a new error

```
Uncaught TypeError: Cannot read property 'top' of undefined
    at n.fn.init.a._position (plugin.js?cdn=%2f%2fbetacontent.anitur.com.tr%2fweb:1904)
    at window.onresize (plugin.js?cdn=%2f%2fbetacontent.anitur.com.tr%2fweb:1904)
```

I change flexdatalist.js and .css but styling problem still goes on thanks for your help

**Comment by sergiodlopes** [comment]
check out the latest draft (1.9.5)

**Comment by recruitname** [comment]
![screenshot_7](https://cloud.githubusercontent.com/assets/25980843/26140886/d00ad8c4-3ae1-11e7-8b05-1c4d4f053c89.jpg)

yes problem has been fixed if you don't check responsive with chrome google device toolbar , so if you wont check responsive with device toolbar It doesn's seem to be a problem. thanks but I guess the script has a little bug on the responsive size take care and take you so much again

**Comment by recruitname** [comment]
absolutely if I've more than one flexdatalist on my page than is broken but if I've just one it's not broken and I have more than 30.000 visitors in a day I gotta change but i liked this autocomplete
