### ISSUE TITLE
Problem with ASP.net results -> Results not passed like expected

### ISSUE THREAD

**Issue by Dattel** [sergiodlopes/jquery-flexdatalist#63]
I figured out that ASP.Net encapsulated the result to the property data.d instead of data.results
So to make results parsed correctly i had to change the getRemoteData Function a bit..

...
$this._getRemoteData = function (data) {
   var _data = data.results ? data.results : data.d? data.d : data;
   ...

**Comment by sergiodlopes** [comment]
Hi,

Thanks. I'll make property name for results as an option.

Sérgio

**Comment by Dattel** [comment]
works great... thanks!!
