### ISSUE TITLE
Problem with ASP.net AJAX Call-> ASP static function not be called...

### ISSUE THREAD

**Issue by Dattel** [sergiodlopes/jquery-flexdatalist#64]
I fixed it by adding contentType: "application/json" to the options....
maybe i am doing something wrong??? or is these line the quick solution?

$this._remote = function (options) {
  // Prevent get data when pressing back button
  if ($this.hasClass('flexdatalist-loading')) {
    return;
  }
  $this.addClass('flexdatalist-loading');
  options = $.extend({
    type: $this._options('requestType'),
    dataType: 'json',
    contentType: "application/json",
    complete: function () {
      $this.removeClass('flexdatalist-loading');
    }
  }, options);
  $.ajax(options);
}`

**Comment by sergiodlopes** [comment]
Hi,

Please check out release v2.0.0, if the bug persists, please, reopen this issue.

Thanks!
Sérgio

**Comment by Dattel** [comment]
doesn't work for me.. but it's okay if i change these two lines for me to make it work.

Line 921: 
     data: data,       -> replaced with data: JSON.stringify(data),
Line 946: additional Line:                              
     contentType: "application/json",

**Comment by sergiodlopes** [comment]
Hi,

Get v.2.0.2 and set option `requestContentType` to `json`, should do the trick.

Thanks,
Sérgio

**Comment by Dattel** [comment]
works great... thanks
