### ISSUE TITLE
How to prevent item removal on Control=disabled

### ISSUE THREAD

**Issue by Dattel** [sergiodlopes/jquery-flexdatalist#67]
Currently there i found no way to disable item removal if the control has been disabled itself.
Would be fine, if the control for multiselection take account of the disabled property of the input control.

**Comment by Dattel** [comment]
could be easyly solved by checking a property on the parent Control:

$inputContainer.find('input').focus();
$li.find('span.fdl-remove').click(function () {
  add Line -------> if ($this.prop("disabled"))
  add Line ------->   return $this;

Same check can be performed to decide whether to render the X for removal

**Comment by sergiodlopes** [comment]
Thanks!

Sérgio
