### ISSUE TITLE
change:flexdatalist event fires only for adding items in multiple mode

### ISSUE THREAD

**Issue by loshuliveros** [sergiodlopes/jquery-flexdatalist#68]
Hi,
i would like to use "change:flexdatalist" event for handling all changes (doc says: "Triggered every time the value in input changes."), but it seems it fires only for adding items. If i remove one, it doesn't trigger event. I tried debug it in chrome dev window, i stopped code process in next step and in console i check value of input by jQuery selector and it was changed correctly - ID of removed item was missing. Is this bug or should i use something else?

**Comment by sergiodlopes** [comment]
Hi,

Please check out release v2.0.0, if the bug persists, please, reopen this issue.

Thanks!
Sérgio
