### ISSUE TITLE
missing event on Item delete for Multiselect

### ISSUE THREAD

**Issue by Dattel** [sergiodlopes/jquery-flexdatalist#69]
Would be fine to have a pendent to the "select:flexdatalist" event on item removal..

**Comment by sergiodlopes** [comment]
Hi,

Yeah, good idea. I'll had it! Thanks.

Sérgio

**Comment by Dattel** [comment]
some remark on this...
-the "select:flexdatalist"-Event sends only the selected item.. (which is okay)
-the "flexdatalist.remove"-Event seems to send an Array of deleted objects with only one element in it (which doesn't make any sense, because there is the "flexdatalist.remove.all"-Event to handle multipe deletions, right?)

**Comment by Dattel** [comment]
sorry for disturbing :-)
i just tested v2.0.3....

```
                    $li.remove();

                    $this
                        .trigger('after:flexdatalist.remove', [$li.data('value'), options])
                        .trigger('change:flexdatalist', [
                            $li.data('value'),
                            $li.data('text'),
                            options
                        ]).trigger('change');
```
$li.data('value') is unfortunately empty at trigger time.... 
shouldn't the event be fired before the $li.remove?

**Comment by sergiodlopes** [comment]
Hi,

No problem. Thanks for bringing that to my attention. Made some improvements also on the code.

Check v.2.0.4
Sérgio

**Comment by Dattel** [comment]
Thanks again for fixing... Feature is working again... 
One small note for completeness on that...
-Insert-Event passes data as complex object
-Remove-Event passes data as stringified....

It not a dramatically one - it's just a remark for parameter alignment
