### ISSUE TITLE
Support api for user filter function and autofocus at first time

### ISSUE THREAD

**Issue by kenzaburo** [sergiodlopes/jquery-flexdatalist#7]
Hey, 

I'm using you plugin but I have some issues, I think it is good if you can improve it. 

1. I need an api to set my filter function because now Im using Firebase, and I need to call an API Firebase filter function. You api function which send POST request can't handle a custom remote filter function. 

2. Input text losts focus everything loading page. Even thought, I set manually autofocus for it.

**Comment by sergiodlopes** [comment]
Hey,

1. Do you call the Firebase API by an HTTP request? Can you give an example?

2. Yeah, I'll fix it today
