### ISSUE TITLE
error when Special characters is input

### ISSUE THREAD

**Issue by codesigner-io** [sergiodlopes/jquery-flexdatalist#70]
if keywords contains Special characters like (, {, etc, there will be some error.

solution: In line 584( in definition of $this._highlight function), change 
new RegExp(keyword, ($this._options('searchContain') ? "ig" : "i")),
to
new RegExp(keyword.replace(/([.*+?^=!:${}()|[\]\/\\])/g, "\\$&"), ($this._options('searchContain') ? "ig" : "i")),

**Comment by Dattel** [comment]
Thanks for pointing out... 
There are some quotation marks missing for me
Must be:
new RegExp(keyword.replace(**"**/([.*+?^=!:${}()|[]/\])/g**"**, "\$&"), ($this._options('searchContain') ? "ig" : "i")),

**Comment by d3sign3r** [comment]
I tried your solution but i am getting this error in firebug error console: "keyword is not defined".  !!!

**Comment by codesigner-io** [comment]
But keyword is the parameter of function _highlight. How can it be not defined? Are you sure you add in the _highlight function?

**Comment by codesigner-io** [comment]
for the new version, it's not line 584. you can just add the line after the definition of _highlight:
$this._highlight = function (keyword, text) {
