### ISSUE TITLE
How to count the results and display them ?

### ISSUE THREAD

**Issue by d3sign3r** [sergiodlopes/jquery-flexdatalist#75]
I noticed that in your demo/examples website that you can display the results and count them by their continent (**eg Europe 50**). How do you do that.??? I tried to make this work but nothing happens :( 

Hope you could help me. Thanks in advance.

**Comment by d3sign3r** [comment]
ok found it. I had to group the results by continent like that: `data-group-by='continent'`

**Comment by sergiodlopes** [comment]
Hi,

Great that you found it. :)

Sérgio
