### ISSUE TITLE
Another Feature suggestion: delayed search

### ISSUE THREAD

**Issue by Dattel** [sergiodlopes/jquery-flexdatalist#79]
Hi,
as i am working with large resultsets and disabled the cache-mode on flexdatalist i ran into problems with the ajax-requests to my backend not coming back enough quickly while the user is typing letters. 
So for myself i added a timer to delay the backend request. Every keytype will restart the timer. So the backend will be queried after a short delay.

Maybe it's a fine addon to make flexdatalist more flexible

Here are the code-changes:

-add a new Option to control the delay:

```
_this._options(
  $this,
  $.extend(
  {
    [...]
    searchDelay: 400,  //add a default delay with 400ms for query
    [...]
```
-rename the original search function
from 
`$this._search = function (callback, keywords) {`
to
`$this._searchDelayed = function (callback, keywords) {`

-add a new searchfunction to handle the delay
```
$this._search = function(callback, keywords){
  //no Delay
  if ($this._options('searchDelay') == 0)
    return this._searchDelayed(callback,keywords);
  //search with delay
  if(this.timer) clearTimeout(this.timer);
  this.timer=setTimeout(this._searchDelayed, $this._options('searchDelay'), callback, keywords);//Start the Query after a short Time.
}
```

**Comment by sergiodlopes** [comment]
Hi,

Good idea for results search (for performance reasons).

For the requests to the backend already exists a similar solution, with the delay time not configurable, though:
https://github.com/sergiodlopes/jquery-flexdatalist/blob/master/jquery.flexdatalist.js#L370

Sérgio

**Comment by sergiodlopes** [comment]
Please check out release v1.9.5.

**Comment by Dattel** [comment]
thanks a lot.. today i updated to 2.0.1 and it's fantastic...
