### ISSUE TITLE
Set/change input default values programmatically

### ISSUE THREAD

**Issue by kialala** [sergiodlopes/jquery-flexdatalist#8]
Hi,

This might sound silly but i'm really just trying to pre-populate the input, with say a simple array like `var preload= ["1","2","3"]`, the elements of the array being the valueProperty parameter of the flexdatalist object. 
It kind of works to just resort to jquery's `val()` but i'm losing the 'tag' effect on Internet Explorer 10... and on Firefox and Chrome, I get the `id` displayed instead of the `name`

It would something along the lines of:

``` javascript

var preload= ["1","2","3"];

$('.flexdatalist').flexdatalist({
       value: preload,
       valueProperty: 'id',
       visibleProperties: ["id","name"],
       searchIn: 'name',
        searchContain: true,
       data: 'somesource.json'
   });
```

Thanks,

**Comment by sergiodlopes** [comment]
Hi,

It appears, from the snippet, that you're trying to use a multiple value input that holds the id's (`valueProperty: 'id'`).
The values must be comma separated:
`<input ... value="1,2,3" multiple>`

Does this help answering your question?

**Comment by kialala** [comment]
Hi,

Here's what the html part would look like, and as i said it does work except on IE.
Say we populate the `<input>` from the get go:
```
<input ... value="1,2,3" class="flexdatalist" textproperty="name" multiple>
```
```javascript
$('.flexdatalist').flexdatalist({
       valueProperty: 'id',
       visibleProperties: ["id","name"],
       searchIn: 'name',
       searchContain: true,
       data: 'somesource.json'
   });
```
IE: NOK, Chrome: OK, Firefox: OK
the problem is, in IE, the input are rendered (taggified) with the "id" rather than the "name"

Or say, i try to populate the `<input>` on the fly with an `array` i received via `.getJSON()`

HTML
```
<input ... class="flexdatalist"  textproperty="name" multiple>
```
Javascript
```javascript
// For simplicity let's suppose the array is structured this way:
var feedArray= ["1", "2", "3"];
$('.flexdatalist').val(feedArray.toString());
$('.flexdatalist').flexdatalist({
       valueProperty: 'id',
       visibleProperties: ["id","name"],
       searchIn: 'name',
       searchContain: true,
       data: 'somesource.json'
   });
```

IE: NOK, Chrome: OK, Firefox: OK
Again, the problem is, in IE, the input are rendered (taggified) with the "id" rather than the "name"

**Comment by sergiodlopes** [comment]
Hi,

Oh, I see. From the first comment I thought it was happenning in all browsers.

It's always IE, right? :)

I'll check it out.

**Comment by sergiodlopes** [comment]
Hi again,

I believe that the problem is that the plugin auto discover's all input's .flexdatalist. So when you set the value, was already initialized.

HTML

`<input ... class="my-name"  data-text-property="name" multiple>`

Javascript:

```
// For simplicity let's suppose the array is structured this way:
var feedArray= ["1", "2", "3"];
$('.my-name').val(feedArray.toString()).flexdatalist({
       valueProperty: 'id',
       visibleProperties: ["id","name"],
       searchIn: 'name',
       searchContain: true,
       data: 'somesource.json'
   });

```

**Comment by kialala** [comment]
Hi Sergio,

As prescribed I tried

HTML
```
<input ... class="my-name" data-text-property="name" multiple>
```
Javascript

```javascript
// For simplicity let's suppose the array is structured this way:
var feedArray= ["1", "2", "3"];
$('.my-name').val(feedArray.toString()).flexdatalist({
       valueProperty: 'id',
       visibleProperties: ["id","name"],
       searchIn: 'name',
       searchContain: true,
       data: 'somesource.json'
   });
```
As I said, I get something really odd on IE, the values are not even "taggified" (image below)...
At this point, I suppose I need to advise the users not to use IE x)) I guess

![ie](https://cloud.githubusercontent.com/assets/20996699/17736531/ba107362-645e-11e6-9d7b-1e4995cec771.PNG)

**Comment by sergiodlopes** [comment]
Hi,

But does the ID's 1, 2, 3 exist in somesource.json?

**Comment by kialala** [comment]
Hi

Yup, Here's how it looks like with Chrome (Firefox):

![chrome](https://cloud.githubusercontent.com/assets/20996699/17736769/095ed2be-6460-11e6-9e32-945ec763298c.PNG)

**Comment by sergiodlopes** [comment]
What version of IE you're using?

**Comment by kialala** [comment]
IE 11 (11.0.9600)

**Comment by sergiodlopes** [comment]
That's really weird. :\

When accessing http://projects.sergiodinislopes.pt/flexdatalist/ (check the example for preset values) from my version of IE (exactly as yours) it works.

![ie11](https://cloud.githubusercontent.com/assets/444252/17737002/9dbfadb2-6482-11e6-97c4-cfe7ed64a8cb.jpg)

**Comment by sergiodlopes** [comment]
What version of flexdatalist you're using btw?

**Comment by kialala** [comment]
Indeed... I checked the example with preset values, it works Ok, even with IE

The thing is, on my project, in IE everything works just fine, like in when I type in i can choose from the scroll down list, the input is taggified, everything works just fine *except* for "default input" .
case 1: Values entered directly as attributes
```
<input ... value="1,2,3" class="flexdatalist" textproperty="name" multiple>
```
or case 2, values entered through javascript:
```javascript
var feedArray= ["1", "2", "3"];
$('.my-name').val(feedArray.toString()).flexdatalist({
       valueProperty: 'id',
       visibleProperties: ["id","name"],
       searchIn: 'name',
       searchContain: true,
       data: 'somesource.json'
   });
```

I used Flexdatalist 1.5.1, updated to 1.5.2, same issue :(

**Comment by sergiodlopes** [comment]
Can you confirm that it doesn't work in both cases/examples you posted (the values set with JS and the values on the input)?

**Comment by kialala** [comment]
yes i confirm it doesn't work in both cases/examples: 
case 1, case 2 even case 1 and case 2 simultaneously

**Comment by sergiodlopes** [comment]
Can you please provide a simple html with some sample of the data in somesource.json with code/snippets?

I honestly don't know what to do in the code without more testing on your concrete example. :\

**Comment by kialala** [comment]
I'll send you that some time this afternoon.

Thanks

**Comment by sergiodlopes** [comment]
Thanks!

**Comment by kialala** [comment]
Hey,

I figured out the problem and the possible solution. 2 things

1- Turns out, in IE you can change the "document mode", looks like I have to use Edge as the default document mode... I cannot even choose IE 11, it goes from 10 to Edge (12?) directly


![ie_works](https://cloud.githubusercontent.com/assets/20996699/17740405/e16c4142-646e-11e6-821b-20c7c4fe648a.PNG)



2- It's just not possible to have the values preset with javascript, the following *don't* work

```javascript
var feedArray= ["1", "2", "3"];
$('.my-name').val(feedArray.toString()).flexdatalist({
       valueProperty: 'id',
       visibleProperties: ["id","name"],
       searchIn: 'name',
       searchContain: true,
       data: 'somesource.json'
   });
```
neither does

```javascript
// For simplicity let's suppose the array is structured this way:
var feedArray= ["1", "2", "3"];
$('.flexdatalist').val(feedArray.toString());
$('.flexdatalist').flexdatalist({
       valueProperty: 'id',
       visibleProperties: ["id","name"],
       searchIn: 'name',
       searchContain: true,
       data: 'somesource.json'
   });
```
I figured out a workaround => affect the values directly in the `<input>` markup, something along the lines of:

```javascript
// For simplicity let's suppose the array is structured this way:
var feedArray= ["1", "2", "3"];

//I had to literally empty and reappend the <div> that wraps the <input> and then affect the values directly to the attr value
 $('#task_wrapper').empty();
$('#task_wrapper').append("<input type='text'  class='flexdatalist' data-value-property='id'  id='tID'   data-selection-required='true'  multiple='multiple' value="+feedArray.toString()+"  name='task_suggestion'>");

$('#tID').flexdatalist({
       valueProperty: 'id',
       visibleProperties: ["id","task"],
       searchIn: 'task',
       textProperty:'task',
       searchContain: true,
       data: 'somesource.json'
   });
```
It's far from being clean, but I really can't think of anything else for now...

**Comment by sergiodlopes** [comment]
Hey,

It's something related to the processing of initial value, for sure. Since the plugin has auto-discovery of all fields with class `.flexdatalist` it will process/initialize without giving the chance to change the input value.

You can either use another class/selector name for the input and then initialize the plugin in your code... or destroy the instance created on page load, change the value and then call the plugin.

```
var feedArray= ["1", "2", "3"];
$('.flexdatalist').flexdatalist('destroy').val(feedArray.toString()).flexdatalist({
       valueProperty: 'id',
       visibleProperties: ["id","name"],
       searchIn: 'name',
       searchContain: true,
       data: 'somesource.json'
   });
```

BTW, using attribute `data-value-property="id"` is the same as `valueProperty: 'id'`, maybe removing that from append() will help cleaning a bit the HTML in it. :)

Having said all of this, making the plugin detect changes to the input value after init and processing them again, would be great. I'll work on that! ;)

**Comment by kialala** [comment]
I have yet to try the `destroy()` method. Will let you know how it turns out to be.

**Comment by sergiodlopes** [comment]
It's now possible to change the value programmatically on release 1.8.0

**Comment by zeckdude** [comment]
@sergiodlopes Amazing plugin! Mad respect! I am running into the issue where I am setting the value on the `flexdatalist` field with jQuery. After I do that, the `flexdatalist` is no longer able to find results. 

These are the steps:

1. Initialize flexdatalist on the input field
2. The autocomplete works great
3. If I breakpoint in the `before:flexdatalist.search` event, I can see the `Data` array has results to search through.
4. I programmatically set the value on the input field (which btw I need to set on both `.flexdatalist-set` and `.flexdatalist-alias`)
5. Now when I remove the contents of the input manually and try to use the autocomplete, it won't work.
6. If I breakpoint in the `before:flexdatalist.search` event now, I can see the `Data` array is empty.

From your last comment it sounded like I should be able to change the value programmatically on the input field without having to re-initialize the `flexdatalist` on the field. Is that correct?

I'm running jQuery v.2.1.4 and flexdatalist v.1.9.2
