### ISSUE TITLE
Send another data with keyword

### ISSUE THREAD

**Issue by budie47** [sergiodlopes/jquery-flexdatalist#80]
Hi Sergio,
I want to send the another data from flexdatalist to the jsp file using ajax. how and what option i should use to get the result? below i attacted my sample code

flexdatalist option

`$('#'+fieldId).flexdatalist({                
minLength: 1,           
searchIn: 'name',                
searchDelay:2000,                      
url:urlData,                
cache:true,                                              
requestType:"POST",
                                                    params:{
                                                        data:{hfc_cd:hfcRISCode},
                                                        timeout:3000,
                                                        success:function(result){
                                                            console.log(result);
                                                            if(result === undefined){
                                                                $('#'+loadingDivId).html('No Record');
                                                            }
                                                        },
                                                    }
                                                 });`

jsp file
`  String key = request.getParameter("keyword");
String hfc_cd = request.getParameter("hfc_cd");
String searchProblem = "select ris_procedure_name from ris_procedure_master where CONCAT(UPPER(ris_procedure_name),LOWER(ris_procedure_name)) like '%" +  key + "%' AND hfc_cd = '"+hfc_cd+"' ";
                             
 ArrayList<ArrayList<String>> search = Conn.getData(searchProblem); `

**Comment by sergiodlopes** [comment]
Hi,

Use `params` option to send `{hfc_cd:hfcRISCode}` and event `after:flexdatalist.data` to set callback after loading data from remote file.

Sérgio

**Comment by sergiodlopes** [comment]
Hi,

Please check out release v2.0.0, if the bug persists, please, reopen this issue.

Thanks!
Sérgio
