### ISSUE TITLE
The control shows that it did not find the record when the record exists

### ISSUE THREAD

**Issue by cmpm72** [sergiodlopes/jquery-flexdatalist#81]
When I have the cache option inactive and the input already has a value filled in the input and the fledatalist will get the value from then url but then says it can not find.

I have seen in the code that the record is being deleted at this location:
                        if (values && values.indexOf($this._getText(item)) > -1) {
                            delete data[i];
                        }
What do I need to do to make it work?

The options I have are:

        var options = {
            textProperty: '{conta}',
            visibleProperties: ['conta', 'descricao', 'ncont'],
            valueProperty: 'conta',
            minLength: 2,
            cache: false,
            focusFirstResult: true,
            selectionRequired: true,
            searchIn: ['conta', 'descricao', 'ncont'],
            url: '../api/GetValues',
            maxShownResults: 7,
            requestType: 'post'
        };

**Comment by sergiodlopes** [comment]
Hi,

> input already has a value filled in the input and the fledatalist will get the value from then url but then says it can not find.

Is the value already in the input the same you're trying to search?

**Comment by cmpm72** [comment]
Hi,

I not trying to search but when then fledatalist take focus do the search.

**Comment by sergiodlopes** [comment]
Not sure I'm understanding... 

Podes escrever em PT pf?

**Comment by cmpm72** [comment]
Ok. Vou também tentar explicar melhor.

Tendo um input text com um valor preenchido quando e feito a ligação ao flexdatalist:
$(element).flexdatalist(options);

Depois quando o controlo  fica com focus vai pedir ao servidor os dados para aquele registo (se fizer a procura no flexdatalist já não faz isso) mas o registo que vem do api e apagado aqui:

if (values && values.indexOf($this._getText(item)) > -1) {
delete data[i];
}

Se fizer a procura no controlo e seleccionar um fica bem e já não faz isso.

**Comment by sergiodlopes** [comment]
Entendi. Ao colocar o input onfocus, ele faz uma busca ao servidor e remove o valor que estava pré-inserido.

É isso, né?

**Comment by cmpm72** [comment]
Não . Por acaso não esta a retirar o valor pré inserido. So faz isso se do servidor não trouxer valores. 
O que acontece e que na lista de resultados aparece a mensagem a dizer que não tem resultados e devia aparecer um registo na lista.

**Comment by sergiodlopes** [comment]
Consegues ver o que o request envia e o que retorna se de facto o valor está presente? No backend existe  uma pesquisa? Está a devolver os resultados correctos? No formato correcto?

`valueProperty: 'conta',`

O `conta `é um ID?

**Comment by cmpm72** [comment]
A conta e uma chave. 
O que vem do servidor e:
[{"conta":"111","descricao":"Descrição da conta","ncont":""}]

No input text esta 111.

Na minha opinião o que acontece e que no método $this._tdata nao deveria apagar as linhas dos valores ja registados no caso de nao utilizar cache.

**Comment by sergiodlopes** [comment]
Na verdade a cache não está a funcionar (foi desativada por dar problemas, espero reativa-la no futuro).

```
if (values && values.indexOf($this._getText(item)) > -1) {
    delete data[i];
}
```
Este código é para prevenir a possibilidade de se seleccionar valores duplicados. É possível permitir valores duplicados (opção `allowDuplicateValues`), mas não me parece ser isso que se pretende no teu caso.

Mas sim, parece ser um bug. O ideal seria preparares uma página teste em que pudesse testar o comportamento do plugin no teu caso em especifico, ou mostrar-me na página de exemplos um input/exemplo que me permita reproduzir o problema, de outra forma, é me complicado ver onde estará o problema e se me é possível resolver rapidamente. :\

O plugin tem de facto alguns problemas e limitações, que pretendo resolver definitivamente numa versão "refactored".

**Comment by cmpm72** [comment]
Obrigado pela resposta.
Apesar de nao ser as mesmas opções no teus exemplos tens um controlo que tem logo portugal preenchido que tem o mesmo problema, ou seja, diz que nao encontrou portugal.
E o que tem o label "And if we want to pre-select a country by is id..."

**Comment by sergiodlopes** [comment]
Ya, entendi...

Não deveria era fazer a pesquisa e consequentemente não mostrar que não tem resultados ao focar o campo. É a isso que te referes?

**Comment by cmpm72** [comment]
Sim. E isso.

**Comment by sergiodlopes** [comment]
:)

Vou resolver isso. Obrigado.

**Comment by cmpm72** [comment]
Obrigado eu.

**Comment by sergiodlopes** [comment]
Verifica a v1.9.6.

Obrigado.

Sérgio

**Comment by cmpm72** [comment]
Esta a funcionar.

Obrigado.
