### ISSUE TITLE
Preloading Only Works for 2 or Fewer Values

### ISSUE THREAD

**Issue by cbautista103** [sergiodlopes/jquery-flexdatalist#82]
After putting together a list of preloaded values or manually loaded values (via $(field).val()), I am only able to get the library to load 2 values—when I attempt to load 3 or more, it simply populates the mock text field with the value string as a query. 2 preloaded values creates a tagged list, but 3 or more results in text. This seems to be happening in all browsers and with all any method of pre-/force-declaring the values.

I've tried hardcoding them in html (value="1, 2, 3, 4"), preloading them with switched-out classes in javascript ($jquery.val("1,2,3,4").addClass('flexdatalist')), and manually loading them post-facto in jquery.

**Comment by sergiodlopes** [comment]
Hi,

Yeah, it's a little buggy when processing after init values. New major release that I'm working on will hopefully improve it.

Cheers!
Sérgio

**Comment by LeclercA** [comment]
Hi,

I add the same issue and I found a 'fix'.

On line 564 of jquery.flexdatalist.js (function ```matches```, we can find this : 

```
if (found.length === 0 || (_options.searchByWord && found.length < (keywords.length - 1))) {
    return false;
}
```
Removing the second condition of the ```if``` statement solved this issue for me. I hope this helps !

**Comment by sergiodlopes** [comment]
Hi,

Please check out release v2.0.0, if the bug persists, please, reopen this issue.

Thanks!
Sérgio
