### ISSUE TITLE
Validation fails - Solved!

### ISSUE THREAD

**Issue by ergousha** [sergiodlopes/jquery-flexdatalist#83]
Hello, Jquery validation fails on flexdata input, because it adds another input control.
Input name was null in original code as:

        $_this = $this
            .clone(false)
            .attr({
                'list': null,
                'name': null,
                'id': ($this.attr('id') ? $this.attr('id') + '-flexdatalist' : null)
            })

I have added name section like id, so I fixed validation based on names.

'name': ($this.attr('name') ? $this.attr('name') + '-flexdatalist' : null),

**Comment by sergiodlopes** [comment]
Hi,

Nice! That fix will be on next release.

Thanks!

Sérgio
