### ISSUE TITLE
Version 2.0.1 - "multiple-keyword" needs to be placed in html-input control now?

### ISSUE THREAD

**Issue by Dattel** [sergiodlopes/jquery-flexdatalist#84]
Hi... thanks for the great Update..
i'm a bit wired about the following fact.

Formerly i added a simple <input>-Control on my page and the JScript to initialize the flextatalist does all the charm... 

Now, if i want to have multiple values, i have to place <input multiple="multiple"> on my page.
Am i wrong or did the option "multiple" on flexdatalist-initialization does not automatically handle these option any more?

**Comment by sergiodlopes** [comment]
Hi,

Fixed. Yeah, it's expected to be 100% compatible with previous version.
New release coming later today (UTC).

Thanks!
Sérgio

**Comment by Dattel** [comment]
nice.. thanks... 
I the meantime i changed my control to support the "multiple" keyword a html-control-base as workaround..

**Comment by sergiodlopes** [comment]
Hi,

Version v2.0.3 handles this correctly.

Thanks!
Sérgio
