### ISSUE TITLE
Version 2.0.1- datalookup on item focus with textproperty

### ISSUE THREAD

**Issue by Dattel** [sergiodlopes/jquery-flexdatalist#85]
Hi again..
it's a cool feature, that the control will query the datasource again if the control got's the focus, but it does not work, if you use the "textProperty".
I know, that i could fix it by simply setting textProperty to "{label}", but maybe there is another way to solve it.

I have the following a DataStructure to be send from my backend to the frontend:
JQueryFlexDataListItem{ 
  string value,
  string label,
  string category,
  int sourceType,
  string thumb
}
these are my control-settings
-groupBy: "category"
-searchIn : "value"
-textProperty: "{category} - {label}"
-valueProperty "['value', 'category', 'sourceType']"
-VisibleProperties: "['label']"

**Comment by sergiodlopes** [comment]
Hi,

Are you talking about a multiple field?

**Comment by Dattel** [comment]
Sorry for not beeing exact with my informations.
No, i am talking about the single selection mode...

The problem occures, if the textpropery consists off multiple fields (category, label in my case).
The next focus on the contol submits the combination (in may case "category - label").
hope that helps a bit.. if not, i can clarify it more tomorrow...

**Comment by sergiodlopes** [comment]
Hi,

Can you set up a demo page? I tested a similar input on the documentation  page and did not saw any problem. Surely there must be something else.

**Comment by Dattel** [comment]
yeah i can....

http://www.faith-clan.de/flexdatalist/flex.html

data.json
```
[
{"value":"1", "label":"Mustermann, Max", "category":"Person", "sourceType": null, "thumb" : null},
{"value":"2", "label":"Mustermann, Moritz", "category":"Person", "sourceType": null, "thumb" : null},
{"value":"3", "label":"Einstein, Albert", "category":"Person", "sourceType": null, "thumb" : null},
{"value":"4", "label":"Musterproject", "category":"Projects", "sourceType": null, "thumb" : null},
{"value":"5", "label":"Testproject, Max", "category":"Projects", "sourceType": null, "thumb" : null},
{"value":"6", "label":"ABC Company, Max", "category":"Company", "sourceType": null, "thumb" : null},
{"value":"7", "label":"Apple, Max", "category":"Company", "sourceType": null, "thumb" : null}
]
```

```
			$('.flexdatalist').flexdatalist({
				minLength: 1,
				searchIn: 'label',
				data: './data.json',
				multiple: false,
				groupBy: 'category',
				textProperty : '{category} - {label}',
				SelectionRequired : true
			});
```

**Comment by sergiodlopes** [comment]
Hi,

Thanks for setting up the page. What browser are you using?

**Comment by sergiodlopes** [comment]
Hi,

Check out release v5.0.5.
Sérgio

**Comment by Dattel** [comment]
Thanks a lot... 
Works much smother now without triggering a search on focus...

Nevertheless the "textPropery" makes much more sense for multiselection (or multiselection with a limit of 1), because on singleselection mode it changes the users input... so for the next search the user has to clear the whole content of the box (since the complete text will be used as search input for the next query)..... but it's totally fine now...

Once more: thanks for the great control.. i really love it!!

Issue closed?

**Comment by sergiodlopes** [comment]
No problem.

Although I agree with you about textProperty better suited for multiple values, I think it's better to leave that control to the web developer. :)

Cheers!
Sérgio
