### ISSUE TITLE
Multiple instance on same page with multiple style (CSS)

### ISSUE THREAD

**Issue by Cariocar** [sergiodlopes/jquery-flexdatalist#88]
Hi,
May I did not find the way to do it, but I have 2 instances of Flexdatalist on the same page, and for both of them the result class is flexdatalist-results and there is no ID to differenciate them.
So CSS is common to the both search results.

I add 2 lines of code in the plugin to manage this by using the ID of the parent field (INPUT one)
Format of the parent ID have to be : anyID_1 // anyID_2 // anyID_3 ... in : 
      `_getResultsContainer function, just after if ($container.length === 0) {`
I get the value of the ID : anyID_1 --> parentID = 1 using this :
      `var $parent_id = $target.attr('id').split('_').pop();`
And I add an ID attribute to the flexdatalist result UL by using this : 
      `$container = $('<ul>').attr('id', 'flexdatalist-results_' + $parent_id)`
>> needed to be secured in case of no numeric ID providing in parent

And in my CSS file, I could manage all flexdatalist-results styles
Hope it should be usefull for others, or integrated directly in the plugin

Regards
Christophe

**Comment by sergiodlopes** [comment]
Hi,

On latest release you should find the the results container has a unique id.

Thanks!
Sérgio
