### ISSUE TITLE
List doesn't show up on re-focus

### ISSUE THREAD

**Issue by NyoCon** [sergiodlopes/jquery-flexdatalist#9]
Hey, it's me again.

I found one more thing, don't know if it's a bug.

Let's say we set minLength to 3. I search for Country names - in this case Germany.
So I type in "Ger" and the list show up.
Now if i remove the focus from the field the list goes invisible.
Then i focus the field again with my previous typed "Ger" but the list only show up again when i remove or add a character.

In my opinion it should show the list on refocus the field if there is a matching text in it.

As I said, don't know if it's a bug but it would be nice to hear from you.

Greetings

**Comment by sergiodlopes** [comment]
Hey,

Not really a bug, but more like something that's missing. I'll implement that later today. Thanks!

Greetings!

**Comment by sergiodlopes** [comment]
Hey,
Fixed on 1.7.0! Thanks for the heads up.

Sérgio
