### ISSUE TITLE
'data' is using POST version 2+ with requestType set to 'get'

### ISSUE THREAD

**Issue by andreasrosenthal** [sergiodlopes/jquery-flexdatalist#90]
Hi,

Thanks for your perfect tool. 

Using the very same code I experience a huge difference between 1.9.6 and 2+

Using 2+: As soon as the user types, a POST request is sent (which is not supported by my api) instead of one load at the initialization I'd expect.

Switching back to the older version 1* everything works like before (GET)

Any hint please on how to proceed? Thanks in advance!

`$('.ChargingId').flexdatalist({
            name: 'ChargingId',
            minLength: 1,
            valueProperty: 'value',
            searchContain: true,
            selectionRequired: true,
            visibleProperties: ["label"],
            searchIn: 'label',
            data: '/api/GetSomething',
            requestType: 'get'
        });`

**Comment by sergiodlopes** [comment]
Hi,

What version are you using?

**Comment by andreasrosenthal** [comment]
2.0.6

**Comment by sergiodlopes** [comment]
Hi,

Download version (2.0.7 WIP) from master branch. Release 2.0.7 will have that fix.

Thanks!

Sérgio

**Comment by andreasrosenthal** [comment]
Hello,

Thanks - that worked. 

Now I have troubles with several instances on one page. Input 3 shows search results from Input 2 sometimes (not clearly reproduceable)

**Comment by sergiodlopes** [comment]
Hi,

I'll take a look at that. Disabling cache should do the trick for now.

Sérgio

**Comment by andreasrosenthal** [comment]
Thank you very much for the ultra fast work around which works perfectly.
