### ISSUE TITLE
selectionRequired: false leads to locked input field

### ISSUE THREAD

**Issue by andreasrosenthal** [sergiodlopes/jquery-flexdatalist#91]
2.07.WIP
multiple lists on one screen, 

Everything works using "selectionRequired: true" with the same code

Switchting to selectionRequired: false
Typing in fields with results in unconsistent behaviour. Typing possible in the beginning for a few characters, no results, then input is locked.

**Comment by sergiodlopes** [comment]
Please, check latest version from master branch (2.0.7 RC).

**Comment by sergiodlopes** [comment]
Released v2.0.7. Should be more stable. Sorry
