### ISSUE TITLE
SHOW ALL RESULTS ON FOCUS with keyboard

### ISSUE THREAD

**Issue by cmpm72** [sergiodlopes/jquery-flexdatalist#92]
In the example, SHOWING ALL RESULTS IN THE FOCUS when entering the control with the keyboard shows the results and disappears.

**Comment by sergiodlopes** [comment]
Hi,

Check release 2.0.7 to see if the problem persists.

Thanks!
Sérgio

**Comment by cmpm72** [comment]
Hi,

I am using that version.

Thanks.

Carlos

**Comment by sergiodlopes** [comment]
Sorry,

Get the v2.0.8 WIP from master branch. The fix will be on next release.

Cheers!
Sérgio

**Comment by cmpm72** [comment]
Hi,

Now I have the following error and I can not see if it works:

jquery.flexdatalist.js:1001 Uncaught TypeError: Cannot read property 'resultsProperty' of undefined
    at Object.extractRemoteData (jquery.flexdatalist.js:1001)
    at Object.success (jquery.flexdatalist.js:990)
    at i (jquery-2.2.4.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-2.2.4.min.js:2)
    at z (jquery-2.2.4.min.js:4)
    at XMLHttpRequest.<anonymous> (jquery-2.2.4.min.js:4)

Following line:

_data = _this.isDefined(data, options.resultsProperty) ? data[options.resultsProperty] : data;

The options is undefined.

**Comment by cmpm72** [comment]
Hi,

This problem is resolved.

Thanks.
