### ISSUE TITLE
How to disabled searching default value?

### ISSUE THREAD

**Issue by recruitname** [sergiodlopes/jquery-flexdatalist#93]
I set default value for my input so when I focus on my input it's trying to search my default value with json but I want to prevent searching when I focus the input I only want to search when I type a something ? how can I do that ?

**Comment by sergiodlopes** [comment]
Hi,

Set option `redoSearchOnFocus` to `false` on this version:
https://github.com/sergiodlopes/jquery-flexdatalist/archive/master.zip

This option will be present on release >=2.1.1

Sérgio

**Comment by recruitname** [comment]
@sergiodlopes  thanks but when I using the new version for example (2.1.1) the plugin gave me a errors

**Comment by sergiodlopes** [comment]
@recruitname can you please post them? What version you were using before?

**Comment by recruitname** [comment]
before 2.1.1 version it was give me a erro but on this version it is not giving any error but also my autocomplete doesn't work and I see any error on console. and it post my json data too.what problem can be ?

**Comment by sergiodlopes** [comment]
@recruitname can you post the configuration you have?

**Comment by recruitname** [comment]
here you are:

`   $('.search-hotels').flexdatalist({
        cache: false,
        requestType: "POST",
        searchDisabled: true,
        searchByWord: true,
        searchContain: true,
        textProperty: '{name}',
        valueProperty: 'seflink',
        maxShownResults: 50,
        minLength: 3,
        focusFirstResult: false,
        selectionRequired: false,
        chainedRelatives: true,
        noResultsText: "{keyword} arama sonucu bulunamadı",
        groupBy: 'category',
        visibleProperties: ["name", "category", "description", "font"],
        searchIn: true,
        relatives: "#checkinplaceholder_relative",
        url: '/ajax/SearchOtel',
    }).on("show:flexdatalist.results", function(ev, result) {
        $.each(result, function(key, value) {
            result[key]['icon_highlight'] = value.font;
        });

    }).on('select:flexdatalist', function(ev, result) {


        $(this).parents(".book-holiday").find(".checkin,#checkin").focus();
        $("#checkinplaceholder").attr("data-baslik-url", result.seflink);

    }).on("before:flexdatalist.data", function() {
        $("#otel-ara .autospin").html("<img src='" + cdnUrl + "/Assets/img/spin.gif' alt='Yukleniyor..'>");


    }).on("after:flexdatalist.data", function() {
        $('.search-hotels').keydown(function(e) {
            if (e.which == 13) {
                $(".otel-ara-submit").trigger("click");
                return false;
            }
        });
        $("#otel-ara .autospin").html("");

    }).on('after:flexdatalist.search', function(ev, result) {

    });
`

**Comment by sergiodlopes** [comment]
@recruitname can you post the error? The error comes from server?

**Comment by recruitname** [comment]
yes this is the warning: plugin.js:1896 Flexdatalist: Search is disabled!
![screenshot_1](https://user-images.githubusercontent.com/25980843/28016964-6a63cc06-657f-11e7-8424-32d205a1a4e9.jpg)

**Comment by sergiodlopes** [comment]
Oh! I see.

Turn debug off:
`debug: false`

**Comment by recruitname** [comment]
no I mean this version is not working on my web site :)

**Comment by sergiodlopes** [comment]
Because of the warning?

**Comment by recruitname** [comment]
the warning is : `search is disabled` yes my search is disable but it was working old version :)

**Comment by sergiodlopes** [comment]
@recruitname check the option to disabled the warning/debug :)

**Comment by recruitname** [comment]
yes problem is still goes on I tried but nothing change please [click to see problem](https://www.anitur.com/) first large text box

**Comment by sergiodlopes** [comment]
@recruitname found the problem!

You have on config:
`searchIn: true,`
change it to 
`searchIn: 'name',`

It should work.

**Comment by recruitname** [comment]
great and very well I loved this version a lot

**Comment by recruitname** [comment]
but redoSearchfocus is not work anyway this is not problem :) I'll try to fix it

**Comment by recruitname** [comment]
I found the problem.
I set searchdisabled as true because I have to use my filter not your autocomplete js filter that's why your filter is prevent my js

**Comment by sergiodlopes** [comment]
@recruitname flexdatalist is focusing a bit too much on it's own search system, it should allow to do the search remotely indeed.

I'll improve that :)

Thanks!

**Comment by recruitname** [comment]
I love so much flexdatalist and I want to use on my web site still despite the problems. only one thing left that I couldn't is search system could we false your filter ? we have our filtering system with asp.net can't we prevent your filter ?

**Comment by recruitname** [comment]
and also it has another bug with value..when I clear my value dynamically clicking by a button then autocomplete it's not searching anymore

**Comment by sergiodlopes** [comment]
@recruitname You don't need the string highlighted?

**Comment by recruitname** [comment]
it was my old issue the problem is now prevent searching on focus and prevent your filter because your filter is prevent my filter on asp.net :)

**Comment by sergiodlopes** [comment]
Check the latest master version. Even with searchDisabled, it should show the results from server... but won't highlight them though.

**Comment by sergiodlopes** [comment]
@recruitname to clear the value, do:
`$('.search-hotels').val('');`

It should do the trick.

**Comment by recruitname** [comment]
yes I need but it's not more important than my current issue. and yes I clear value with val if you check it out on responsive you will see (767px) and after writing a something if you click (x) button then autocompete won't work

**Comment by sergiodlopes** [comment]
@recruitname You could also enable cache, it works very well now and improves performance alot. ;)

**Comment by sergiodlopes** [comment]
@recruitname sorry, checking that empty/clear value problem...

**Comment by recruitname** [comment]
I swear to god I'll use this plugin whatever happens

**Comment by sergiodlopes** [comment]
@recruitname after searching the code on https://www.anitur.com/, it shows you're not using the version on master:
https://github.com/sergiodlopes/jquery-flexdatalist/archive/master.zip

It will fix that value problem. really. If you group all files in one, make sure the latest version is really there, loaded.

**Comment by recruitname** [comment]
@sergiodlopes  I had to change with old version because my web site has more than 500 instant.after the new version I will add

**Comment by recruitname** [comment]
@sergiodlopes thanks it's work now thank you so much

**Comment by sergiodlopes** [comment]
@recruitname Yeah, I understand :)

The search disabled fix/master version is now on release 2.1.1
https://github.com/sergiodlopes/jquery-flexdatalist/releases

Try enabling cache, your users should have a better/speedy experience, since it prevents requesting the same data again from server. cacheLifetime is in 60 seconds, but you can change that, ofcourse. Check documentation. ;)

Glad it works well now.
Thanks for bringing to my attention the best way to handle searchDisabled.

Sérgio

**Comment by recruitname** [comment]
@sergiodlopes  thanks for everything you are so friendly I set `cache:true` thanks again:)
