### ISSUE TITLE
How to add AJAX option

### ISSUE THREAD

**Issue by loshuliveros** [sergiodlopes/jquery-flexdatalist#97]
Hi Sergio,
am i able add new Ajax options. I use CORS and i need add this: xhrFields: { withCredentials: true }

Thanks for reply

Vlad

**Comment by sergiodlopes** [comment]
Hi,

Sorry, not possible at the moment. I'll improve that!

Thanks!
Sérgio

**Comment by loshuliveros** [comment]
Thank You!
